add_variables_to_input – JSON-Fortran
add_variables_to_input Subroutine
Source File
public subroutine add_variables_to_input(me, variable, units, frame, center, rdata, error_cnt)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(len=*), intent(in) :: variable
character(len=*), intent(in) :: units
character(len=*), intent(in) :: frame
character(len=*), intent(in) :: center
real(kind=wp), intent(in), dimension(:) :: rdata
integer, intent(inout) :: error_cnt
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: var
Source Code
    subroutine add_variables_to_input(me, variable, units, frame, center, rdata, error_cnt)
    !Used by test_2.
    implicit none
    type(json_value),pointer :: me
    character(len=*),intent(in) :: variable, units, frame, center
    real(wp),dimension(:),intent(in) :: rdata
    integer, intent(inout) :: error_cnt
    type(json_value),pointer :: var        !a variable in the trajectory:
    !initialize:
    nullify(var)
    !create the object before data can be added:
    call json_create_object(var,'')    !name does not matter
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    !variable info:
    call json_add(var, 'VARIABLE',trim(variable))
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(var, 'UNITS', trim(units))
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(var, 'FRAME', trim(frame))
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_add(var, 'CENTER', trim(center))
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    !trajectory [vector of reals]:
    call json_add(var, 'DATA', rdata)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    !add this variable to trajectory structure:
    call json_add(me, var)
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    !cleanup:
    nullify(var)
    end subroutine add_variables_to_input
Call graph
add_variables_to_input calls json_print_error_message, json_add, json_create_object, json_failed
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_create_object calls json_value_create_object, wrap_json_value_create_object
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_unicode calls to_uni_vec, to_uni
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
json_value_create_object calls json_value_create, to_object
wrap_json_value_create_object calls to_unicode, json_value_create_object
to_object calls destroy_json_data
test_2 calls add_variables_to_input
jf_test_2 calls test_2