destroy_json_data – JSON-Fortran
destroy_json_data Subroutine
Jacob Williams
Source File
private subroutine destroy_json_data(d)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(inout) :: d
Description
Destroy the data within a json_value, and rest type to json_unknown.
Called By
Source Code
    subroutine destroy_json_data(d)
    implicit none
    type(json_value),intent(inout) :: d
    d%var_type = json_unknown
    if (allocated(d%log_value)) deallocate(d%log_value)
    if (allocated(d%int_value)) deallocate(d%int_value)
    if (allocated(d%dbl_value)) deallocate(d%dbl_value)
    if (allocated(d%str_value)) deallocate(d%str_value)
    end subroutine destroy_json_data
Call graph
to_double calls destroy_json_data
to_null calls destroy_json_data
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
to_integer calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
to_logical calls destroy_json_data
parse_number calls to_double, to_integer
json_value_add_double calls to_double, json_add
json_value_create_double calls to_double
json_update_double calls to_double, json_add
parse_value calls to_null, to_array, to_string, to_object, to_logical, parse_number, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object, json_add, json_destroy
json_parse_string calls parse_value
parse_array calls parse_value, json_add, json_destroy
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse, json_destroy
test_8 calls json_parse, json_destroy
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_value_add_double calls json_value_add_double
json_add calls json_value_add_double, wrap_json_value_add_double, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_integer, json_value_add_double_vec, json_value_add_string, json_value_add_logical, wrap_json_value_add_integer_vec, json_value_add_string_vec_name_ascii, wrap_json_value_add_string_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, wrap_json_value_add_double_vec, json_value_add_string_name_ascii, wrap_json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_logical
json_value_add_integer_vec calls to_array, json_add
json_value_add_string_vec calls to_array, json_add
json_value_add_logical_vec calls to_array, json_add
json_update_logical calls to_logical, json_add
json_update_string calls to_string, json_add
json_update_integer calls to_integer, json_add
json_value_add_integer calls to_integer, json_add
test_2 calls json_add, add_variables_to_input, json_update, json_create_array, json_create_object, json_destroy
json_value_add_double_vec calls to_array, json_add
test_12 calls json_add, json_update, json_create_object
test_7 calls json_add, json_create_array, json_create_object, json_remove, json_destroy
json_value_add_string calls to_string, json_add
json_value_add_logical calls to_logical, json_add
test_4 calls json_add, json_create_object, json_destroy
add_variables_to_input calls json_add, json_create_object
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
wrap_json_update_logical calls json_update_logical
json_update calls json_update_double, json_update_logical, json_update_string, json_update_integer, wrap_json_update_logical, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer, wrap_json_update_double
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update, json_remove
rename calls json_update
test_10 calls json_update, json_create_double, json_create_null, json_create_string, json_create_object, json_create_integer, json_remove_if_present, json_destroy, json_create_logical
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
wrap_json_value_add_integer calls json_value_add_integer
jf_test_2 calls test_2
wrap_json_value_add_double_vec calls json_value_add_double_vec
jf_test_12 calls test_12
jf_test_7 calls test_7
json_value_add_string_name_ascii calls json_value_add_string
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
wrap_json_value_add_logical calls json_value_add_logical
jf_test_4 calls test_4
wrap_json_value_create_double calls json_value_create_double
json_create_double calls json_value_create_double, wrap_json_value_create_double
wrap_json_update_double calls json_update_double
json_value_create_null calls to_null
wrap_json_value_create_null calls json_value_create_null
json_create_null calls json_value_create_null, wrap_json_value_create_null
json_value_create_array calls to_array
wrap_json_value_create_array calls json_value_create_array
json_create_array calls json_value_create_array, wrap_json_value_create_array
json_value_create_string calls to_string
wrap_json_value_create_string calls json_value_create_string
json_create_string calls json_value_create_string, wrap_json_value_create_string
json_value_create_object calls to_object
wrap_json_value_create_object calls json_value_create_object
json_create_object calls json_value_create_object, wrap_json_value_create_object
json_value_create_integer calls to_integer
wrap_json_value_create_integer calls json_value_create_integer
json_create_integer calls json_value_create_integer, wrap_json_value_create_integer
json_file_destroy calls json_value_destroy
json_value_remove calls json_value_destroy
json_remove calls json_value_remove
json_value_remove_if_present calls json_remove
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
json_destroy calls json_value_destroy
json_value_create_logical calls to_logical
wrap_json_value_create_logical calls json_value_create_logical
json_create_logical calls json_value_create_logical, wrap_json_value_create_logical