escape_string – JSON-Fortran
escape_string Subroutine
Jacob Williams
1/21/2014
Source File
private subroutine escape_string(str_in, str_out)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str_in
character(kind=CK,len=:), intent(out), allocatable :: str_out
Description
Add the escape characters to a string for adding to JSON.
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
integer(kind=IK), public :: ipos
character(kind=CK,len=1), public :: c
character(kind=CK,len=*), public, parameter :: specials = quotation_mark//backslash//slash//bspace//formfeed//newline//carriage_return//horizontal_tab
Source Code
    subroutine escape_string(str_in, str_out)
    implicit none
    character(kind=CK,len=*),intent(in)              :: str_in
    character(kind=CK,len=:),allocatable,intent(out) :: str_out
    integer(IK) :: i,ipos
    character(kind=CK,len=1) :: c
    character(kind=CK,len=*),parameter :: specials = quotation_mark//&
                                                     backslash//&
                                                     slash//&
                                                     bspace//&
                                                     formfeed//&
                                                     newline//&
                                                     carriage_return//&
                                                     horizontal_tab
    !Do a quick scan for the special characters,
    ! if any are present, then process the string,
    ! otherwise, return the string as is.
    if (scan(str_in,specials)>0) then
        str_out = repeat(space,chunk_size)
        ipos = 1
        !go through the string and look for special characters:
        do i=1,len(str_in)
            c = str_in(i:i)    !get next character in the input string
            !if the string is not big enough, then add another chunk:
            if (ipos+3>len(str_out)) str_out = str_out // repeat(space, chunk_size)
            select case(c)
            case(quotation_mark,backslash,slash)
                str_out(ipos:ipos+1) = backslash//c
                ipos = ipos + 2
            case(bspace)
                str_out(ipos:ipos+1) = '\b'
                ipos = ipos + 2
            case(formfeed)
                str_out(ipos:ipos+1) = '\f'
                ipos = ipos + 2
            case(newline)
                str_out(ipos:ipos+1) = '\n'
                ipos = ipos + 2
            case(carriage_return)
                str_out(ipos:ipos+1) = '\r'
                ipos = ipos + 2
            case(horizontal_tab)
                str_out(ipos:ipos+1) = '\t'
                ipos = ipos + 2
            case default
                str_out(ipos:ipos) = c
                ipos = ipos + 1
            end select
        end do
        !trim the string if necessary:
        if (ipos<len(str_out)+1) then
            if (ipos==1) then
                str_out = ''
            else
                str_out = str_out(1:ipos-1)
            end if
        end if
    else
        str_out = str_in
    end if
    end subroutine escape_string
Call graph
json_value_add_string calls escape_string, json_add
json_value_add_string_name_ascii calls json_value_add_string
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
json_add calls json_value_add_string, json_value_add_string_name_ascii, wrap_json_value_add_string, json_value_add_string_val_ascii, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_integer, json_value_add_double_vec, json_value_add_double, json_value_add_logical, wrap_json_value_add_integer_vec, json_value_add_string_vec_name_ascii, wrap_json_value_add_string_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, wrap_json_value_add_double_vec, wrap_json_value_add_double, wrap_json_value_add_logical
parse_object calls json_add, parse_object, parse_value
parse_array calls json_add, parse_value
json_value_add_integer_vec calls json_add
json_value_add_string_vec calls json_add
json_value_add_logical_vec calls json_add
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_update_integer calls json_add
json_value_add_integer calls json_add
test_2 calls json_add, add_variables_to_input, json_update
json_value_add_double_vec calls json_add
test_12 calls json_add, json_update
json_value_add_double calls json_add
test_7 calls json_add
json_value_add_logical calls json_add
test_4 calls json_add
add_variables_to_input calls json_add
parse_value calls parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_string, json_update_integer, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
wrap_json_value_add_integer calls json_value_add_integer
jf_test_2 calls test_2
wrap_json_value_add_double_vec calls json_value_add_double_vec
jf_test_12 calls test_12
wrap_json_value_add_double calls json_value_add_double
jf_test_7 calls test_7
wrap_json_value_add_logical calls json_value_add_logical
jf_test_4 calls test_4