integer_to_string – JSON-Fortran
integer_to_string Subroutine
Jacob Williams
12/4/2013
Source File
private pure subroutine integer_to_string(ival, str)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: ival
integer value.
character(kind=CK,len=*), intent(out) :: str
ival converted to a string.
Description
Convert an integer to a string.
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: istat
Source Code
    pure subroutine integer_to_string(ival,str)
    implicit none
    integer(IK),intent(in)               :: ival  !! integer value.
    character(kind=CK,len=*),intent(out) :: str   !! ival converted to a string.
    integer(IK) :: istat
    write(str,fmt=int_fmt,iostat=istat) ival
    if (istat==0) then
        str = adjustl(str)
    else
        str = repeat(star,len(str))
    end if
    end subroutine integer_to_string
Call graph
push_char calls integer_to_string
annotate_invalid_json calls integer_to_string
json_value_print calls integer_to_string, json_value_print
parse_number calls push_char
parse_value calls push_char, parse_number, parse_object, parse_array
json_parse_file calls annotate_invalid_json, parse_value
parse_object calls parse_value, parse_object
json_parse_string calls annotate_invalid_json, parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse, json_print
test_8 calls json_parse, json_print
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
json_print_1 calls json_value_print
json_value_to_string calls json_value_print
json_file_print_1 calls json_value_print
json_file_print_to_console calls json_value_print
json_print calls json_print_1, json_print_2
json_print_2 calls json_print
test_2 calls json_print
test_12 calls json_print
test_7 calls json_print
test_4 calls json_print, json_print_to_string
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string