json_throw_exception – JSON-Fortran
json_throw_exception Subroutine
Jacob Williams
12/4/2013
Source File
private subroutine json_throw_exception(msg)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: msg
Description
Throw an exception in the JSON module. This routine sets the error flag, and prevents any subsequent routine from doing anything, until json_clear_exceptions is called.
Called By
Source Code
    subroutine json_throw_exception(msg)
    implicit none
    character(kind=CK,len=*),intent(in) :: msg    !the error message
    exception_thrown = .true.
    err_message = trim(msg)
    if (is_verbose) then
        write(*,'(A)') '***********************'
        write(*,'(A)') 'JSON-Fortran EXCEPTION: '//trim(msg)
        !call backtrace()     ! gfortran (use -fbacktrace -fall-intrinsics flags)
        !call tracebackqq(-1) ! intel (requires "use ifcore" in this routine)
        write(*,'(A)') '***********************'
    end if
    end subroutine json_throw_exception
Call graph
wrap_json_throw_exception calls json_throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_value calls throw_exception, parse_number, parse_object, parse_array, parse_string, push_char, parse_for_chars
json_value_print calls throw_exception, json_value_print
json_update_string calls throw_exception, json_get
json_get_double calls throw_exception
parse_number calls throw_exception, push_char, string_to_double, string_to_integer
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path
parse_object calls throw_exception, parse_value, parse_object, parse_string
json_get_by_path calls throw_exception, string_to_integer, json_get_child
json_get_array_with_path calls throw_exception, json_get_by_path, json_get_array
parse_array calls throw_exception, parse_value
parse_string calls throw_exception
push_char calls throw_exception
json_print_2 calls throw_exception, json_print
json_get_string_with_path calls throw_exception, json_get_by_path, json_get_string
json_get_logical calls throw_exception
json_update_integer calls throw_exception, json_get
json_value_get_by_index calls throw_exception
json_value_get_by_name_chars calls throw_exception
json_file_print_1 calls throw_exception, json_value_print
json_get_logical_with_path calls throw_exception, json_get_by_path, json_get_logical
json_file_move_pointer calls throw_exception
json_update_double calls throw_exception, json_get
string_to_double calls throw_exception
json_get_string calls throw_exception, unescape_string
json_get_array calls throw_exception
json_file_print_2 calls throw_exception
unescape_string calls throw_exception
json_parse_file calls throw_exception, parse_value, json_initialize
string_to_integer calls throw_exception
json_update_logical calls throw_exception, json_get
json_get_integer calls throw_exception
json_initialize calls throw_exception
json_get_integer_with_path calls throw_exception, json_get_by_path, json_get_integer
parse_for_chars calls throw_exception
json_print_1 calls throw_exception, json_value_print
json_parse_string calls parse_value, json_initialize
wrap_json_parse_string calls json_parse_string
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_initialize, json_parse, json_print
test_8 calls json_initialize, json_parse, json_print
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
json_value_to_string calls json_value_print
json_file_print_to_console calls json_value_print
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string
test_4 calls json_initialize, json_print_to_string, json_print
jf_test_4 calls test_4
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_integer, json_update_double, json_update_logical, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer, wrap_json_update_double, wrap_json_update_logical
test_12 calls json_initialize, json_update, json_get, json_print
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_initialize, json_update
rename calls json_update, json_get
test_10 calls json_initialize, json_update, json_get, json_remove_if_present
test_2 calls json_initialize, json_update, json_get, json_print
json_file_update_real calls json_update
jf_test_12 calls test_12
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
jf_test_2 calls test_2
wrap_json_file_update_real calls json_file_update_real
json_get calls json_get_double, json_get_double_with_path, json_get_by_path, json_get_array_with_path, json_get_string_with_path, json_get_logical, json_get_logical_with_path, json_get_string, json_get_array, json_get_integer, json_get_integer_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_double_with_path, wrap_json_get_by_path, wrap_json_get_array_with_path, wrap_json_get_string_with_path, wrap_json_get_logical_with_path, wrap_json_get_integer_with_path
json_get_integer_vec_with_path calls json_get
json_file_get_integer_vec calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_get_double_vec_with_path calls json_get
test_7 calls json_initialize, json_get, json_print, json_get_child
json_file_get_logical calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
json_file_get_string_vec calls json_get
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
wrap_json_file_get_string_vec calls json_file_get_string_vec
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_by_path calls json_get_by_path
json_file_get_object calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_array_with_path calls json_get_array_with_path
json_print calls json_print_2, json_print_1
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_update_integer calls json_update_integer
json_get_child calls json_value_get_by_index, json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars
wrap_json_get_logical_with_path calls json_get_logical_with_path
wrap_json_update_double calls json_update_double
wrap_json_update_logical calls json_update_logical
test_6 calls json_initialize
test_5 calls json_initialize
test_11 calls json_initialize
test_13 calls json_initialize
test_3 calls json_initialize
test_9 calls json_initialize
jf_test_6 calls test_6
jf_test_5 calls test_5
jf_test_11 calls test_11
jf_test_13 calls test_13
jf_test_3 calls test_3
jf_test_9 calls test_9
wrap_json_get_integer_with_path calls json_get_integer_with_path