json_value_destroy – JSON-Fortran
json_value_destroy Subroutine
Jacob Williams
1/22/2014
Source File
private recursive subroutine json_value_destroy(me, destroy_next)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
logical(kind=LK), intent(in), optional :: destroy_next
if true, then me%next is also destroyed (default is true)
Description
Destroy a json_value linked-list structure.
Note
The original FSON version of this routine was not properly freeing the memory. It was rewritten.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical(kind=LK), public :: des_next
type(json_value), public, pointer :: p
Source Code
    recursive subroutine json_value_destroy(me,destroy_next)
    implicit none
    type(json_value),pointer :: me
    logical(LK),intent(in),optional :: destroy_next  !! if true, then me%next is also destroyed (default is true)
    logical(LK) :: des_next
    type(json_value), pointer :: p
    if (associated(me)) then
        if (present(destroy_next)) then
            des_next = destroy_next
        else
            des_next = .true.
        end if
        if (allocated(me%name)) deallocate(me%name)
        call destroy_json_data(me)
        if (associated(me%children)) then
            do while (me%n_children > 0)
                p => me%children
                me%children => me%children%next
                me%n_children = me%n_children - 1
                call json_value_destroy(p,.false.)
            end do
            nullify(me%children)
            nullify(p)
        end if
        if (associated(me%next) .and. des_next) call json_value_destroy(me%next)
        if (associated(me%previous)) nullify(me%previous)
        if (associated(me%parent))   nullify(me%parent)
        if (associated(me%tail))     nullify(me%tail)
        deallocate(me)
        nullify(me)
    end if
    end subroutine json_value_destroy
Call graph
json_value_destroy calls json_value_destroy, destroy_json_data
json_file_destroy calls json_value_destroy
json_value_remove calls json_value_destroy
json_remove calls json_value_remove
test_7 calls json_remove, json_destroy
json_value_remove_if_present calls json_remove
test_1 calls json_remove
jf_test_7 calls test_7
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
test_10 calls json_remove_if_present, json_destroy
jf_test_10 calls test_10
jf_test_1 calls test_1
json_destroy calls json_value_destroy
parse_array calls json_destroy, parse_value
test_2 calls json_destroy
test_14 calls json_destroy, json_parse
parse_object calls json_destroy, parse_object, parse_value
test_4 calls json_destroy
test_8 calls json_destroy, json_parse
parse_value calls parse_array, parse_object
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
json_file_load_from_string calls json_parse
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
jf_test_2 calls test_2
jf_test_14 calls test_14
jf_test_4 calls test_4
jf_test_8 calls test_8