json_parse_string – JSON-Fortran
json_parse_string Subroutine
Source File
private subroutine json_parse_string(p, str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
output structure
character(kind=CK,len=*), intent(in) :: str
string with JSON data
Description
Parse the JSON string and populate the json_value tree.
See also
json_parse_file
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public, parameter :: iunit = 0
Source Code
    subroutine json_parse_string(p, str)
    implicit none
    type(json_value),pointer            :: p     !! output structure
    character(kind=CK,len=*),intent(in) :: str   !! string with JSON data
    integer(IK),parameter :: iunit = 0 !indicates that json data will be read from buffer
    if ( .not. exception_thrown ) then
        !clear any exceptions and initialize:
        call json_initialize()
        ! create the value and associate the pointer
        call json_value_create(p)
        ! Note: the name of the root json_value doesn't really matter,
        !  but we'll allocate something here just in case.
        p%name = ''
        ! parse as a value
        call parse_value(unit=iunit, str=str, value=p)
        if (exception_thrown) call annotate_invalid_json(iunit,str)
    end if
    end subroutine json_parse_string
Call graph
json_parse_string calls parse_value, annotate_invalid_json, json_initialize, json_value_create
parse_value calls parse_array, throw_exception, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object, pop_char
annotate_invalid_json calls integer_to_string, get_current_line_from_file_stream, get_current_line_from_file_sequential
json_initialize calls throw_exception, json_clear_exceptions
parse_array calls parse_value, json_value_create, throw_exception, pop_char, json_destroy, json_add
throw_exception calls json_throw_exception, wrap_json_throw_exception
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, push_char, pop_char, to_integer, to_double, string_to_integer, string_to_double
parse_object calls parse_value, json_value_create, throw_exception, parse_string, parse_object, pop_char, json_destroy, json_add
json_destroy calls json_value_destroy
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_destroy calls json_value_destroy, destroy_json_data
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_value_create, json_add, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_unicode calls to_uni_vec, to_uni
to_integer calls destroy_json_data
to_double calls destroy_json_data
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
string_to_double calls throw_exception
wrap_json_parse_string calls json_parse_string
json_parse calls json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string