json_parse_file – JSON-Fortran
json_parse_file Subroutine
Source File
private subroutine json_parse_file(file, p, unit)
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in) :: file
JSON file name
type(json_value), , pointer :: p
output structure
integer(kind=IK), intent(in), optional :: unit
file unit number (/= 0)
Description
Parse the JSON file and populate the json_value tree.
Inputs
The inputs can be:
file and unit : the specified unit is used to read JSON from file. [note if unit is already open, then the filename is ignored]
file : JSON is read from file using internal unit number
Example
    type(json_value),pointer :: p
    call json_parse(file='myfile.json', p=p)
History
Jacob Williams : 01/13/2015 : added read from string option.
Izaak Beekman : 03/08/2015 : moved read from string to separate subroutine, and error annotation to separate subroutine.
Note
When calling this routine, any exceptions thrown from previous calls will automatically be cleared.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: iunit
integer(kind=IK), public :: istat
logical(kind=LK), public :: is_open
Source Code
    subroutine json_parse_file(file, p, unit)
    implicit none
    character(kind=CDK,len=*),intent(in) :: file  !! JSON file name
    type(json_value),pointer             :: p     !! output structure
    integer(IK),intent(in),optional      :: unit  !! file unit number (/= 0)
    integer(IK) :: iunit, istat
    logical(LK) :: is_open
    !clear any exceptions and initialize:
    call json_initialize()
    if ( present(unit) ) then
        if (unit==0) then
            call throw_exception('Error in json_parse_file: unit number must not be 0.')
            return
        end if
        iunit = unit
        !check to see if the file is already open
        ! if it is, then use it, otherwise open the file with the name given.
        inquire(unit=iunit, opened=is_open, iostat=istat)
        if (istat==0 .and. .not. is_open) then
           ! open the file
            open (  unit        = iunit, &
                    file        = file, &
                    status      = 'OLD', &
                    action      = 'READ', &
                    form        = form_spec, &
                    access      = access_spec, &
                    iostat      = istat &
                    FILE_ENCODING )
        else
            !if the file is already open, then we need to make sure
            ! that it is open with the correct form/access/etc...
        end if
    else
        ! open the file with a new unit number:
        open (  newunit     = iunit, &
                file        = file, &
                status      = 'OLD', &
                action      = 'READ', &
                form        = form_spec, &
                access      = access_spec, &
                iostat      = istat &
                FILE_ENCODING )
    end if
    if (istat==0) then
        ! create the value and associate the pointer
        call json_value_create(p)
        ! Note: the name of the root json_value doesn't really matter,
        !  but we'll allocate something here just in case.
        p%name = trim(file)  !use the file name
        ! parse as a value
        call parse_value(unit=iunit, str=CK_'', value=p)
        if (exception_thrown) call annotate_invalid_json(iunit,CK_'')
        ! close the file if necessary
        close(unit=iunit, iostat=istat)
    else
        call throw_exception('Error in json_parse_file: Error opening file: '//trim(file))
        nullify(p)
    end if
    end subroutine json_parse_file
Call graph
json_parse_file calls json_value_create, annotate_invalid_json, parse_value, json_initialize, throw_exception
annotate_invalid_json calls get_current_line_from_file_stream, integer_to_string, get_current_line_from_file_sequential
parse_value calls throw_exception, parse_array, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object, pop_char
json_initialize calls throw_exception, json_clear_exceptions
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_array calls json_value_create, parse_value, throw_exception, pop_char, json_destroy, json_add
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, push_char, pop_char, to_integer, to_double, string_to_integer, string_to_double
parse_object calls json_value_create, parse_value, throw_exception, parse_string, parse_object, pop_char, json_destroy, json_add
json_destroy calls json_value_destroy
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_destroy calls json_value_destroy, destroy_json_data
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_value_create, json_add, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_unicode calls to_uni_vec, to_uni
to_integer calls destroy_json_data
to_double calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_parse calls json_parse_file
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string