json_failed – JSON-Fortran
json_failed Function
Jacob Williams
12/5/2013
Source File
public function json_failed() result(failed)
Arguments
None
Return Value logical(kind=LK)
Description
Logical function to indicate if an exception has been thrown.
Example
    type(json_file) :: json
    logical :: status_ok
    character(len=:),allocatable :: error_msg
    call json%load_file(filename='myfile.json')
    if (json_failed()) then
        call json_check_for_errors(status_ok, error_msg)
        write(*,*) 'Error: '//error_msg
        call json_clear_exceptions()
        call json%destroy()
    end if
See also
json_check_for_errors
Called By
Source Code
    function json_failed() result(failed)
    implicit none
    logical(LK) :: failed
    failed = exception_thrown
    end function json_failed
Call graph
test_11 calls json_failed
test_6 calls json_failed
test_9 calls json_failed
test_3 calls json_failed
test_7 calls json_failed
add_variables_to_input calls json_failed
test_2 calls json_failed, add_variables_to_input
test_8 calls json_failed
test_4 calls json_failed
test_13 calls json_failed
test_5 calls json_failed
test_10 calls json_failed
test_14 calls json_failed
test_1 calls json_failed
jf_test_11 calls test_11
jf_test_6 calls test_6
jf_test_9 calls test_9
jf_test_3 calls test_3
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_8 calls test_8
jf_test_4 calls test_4
jf_test_13 calls test_13
test_12 calls check_errors
jf_test_12 calls test_12
jf_test_5 calls test_5
jf_test_10 calls test_10
jf_test_14 calls test_14
jf_test_1 calls test_1