json_get_by_path – JSON-Fortran
json_get_by_path Subroutine
Source File
private subroutine json_get_by_path(me, path, p, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
type(json_value), intent(out), pointer :: p
logical(kind=LK), intent(out), optional :: found
true if it was found
Description
Returns the json_value pointer given the path string.
Example
     type(json_value),pointer :: dat,p
     logical :: found
     !...
     call json_get(dat,'data(2).version',p,found)
Notes
The following special characters are used to denote paths:
  $         - root
  @         - this
  .         - child object member
  [] or ()  - child array element
Thus, if any of these characters are present in the name key, this routine cannot be used to get the value. In that case, the json_get_child routines would need to be used.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=1), public, parameter :: start_array_alt = '('
character(kind=CK,len=1), public, parameter :: end_array_alt = ')'
character(kind=CK,len=1), public, parameter :: root = '$'
character(kind=CK,len=1), public, parameter :: this = '@'
character(kind=CK,len=1), public, parameter :: child = '.'
integer(kind=IK), public :: i
integer(kind=IK), public :: length
integer(kind=IK), public :: child_i
character(kind=CK,len=1), public :: c
logical(kind=LK), public :: array
type(json_value), public, pointer :: tmp
Source Code
    subroutine json_get_by_path(me, path, p, found)
    implicit none
    type(json_value),pointer,intent(in)  :: me
    character(kind=CK,len=*),intent(in)  :: path
    type(json_value),pointer,intent(out) :: p
    logical(LK),intent(out),optional     :: found  !! true if it was found
    character(kind=CK,len=1),parameter :: start_array_alt = '('
    character(kind=CK,len=1),parameter :: end_array_alt   = ')'
    character(kind=CK,len=1),parameter :: root            = '$'
    character(kind=CK,len=1),parameter :: this            = '@'
    character(kind=CK,len=1),parameter :: child           = '.'
    integer(IK)              :: i,length,child_i
    character(kind=CK,len=1) :: c
    logical(LK)              :: array
    type(json_value),pointer :: tmp
    if (.not. exception_thrown) then
        nullify(p)
        ! default to assuming relative to this
        p => me
        child_i = 1
        array = .false.
        length = len_trim(path)
        do i=1, length
            c = path(i:i)
            select case (c)
            case (root)
                ! root
                do while (associated (p%parent))
                    p => p%parent
                end do
                child_i = i + 1
            case (this)
                ! this
                p => me
                child_i = i + 1
            case (child)
                ! get child member from p
                if (child_i < i) then
                    nullify(tmp)
                    call json_get_child(p, path(child_i:i-1), tmp)
                    p => tmp
                    nullify(tmp)
                else
                    child_i = i + 1
                    cycle
                end if
                if (.not. associated(p)) then
                    call throw_exception('Error in json_get_by_path:'//&
                                         ' Error getting child member.')
                    exit
                end if
                child_i = i+1
            case (start_array,start_array_alt)
                !....Modified to allow for 'var[3]' style syntax
                !Note: jmozmoz/fson has a slightly different version of this...
                ! start looking for the array element index
                array = .true.
                ! get child member from p
                if (child_i < i) then
                    nullify(tmp)
                    call json_get_child(p, path(child_i:i-1), tmp)
                    p => tmp
                    nullify(tmp)
                else
                    child_i = i + 1
                    cycle
                end if
                if (.not. associated(p)) then
                    call throw_exception('Error in json_get_by_path:'//&
                                         ' Error getting array element')
                    exit
                end if
                child_i = i + 1
            case (end_array,end_array_alt)
                if (.not.array) then
                    call throw_exception('Error in json_get_by_path: Unexpected ]')
                    exit
                end if
                array = .false.
                child_i = string_to_integer(path(child_i:i-1))
                nullify(tmp)
                call json_get_child(p, child_i, tmp)
                p => tmp
                nullify(tmp)
                child_i= i + 1
            end select
        end do
        if (exception_thrown) then
            if (present(found)) then
                found = .false.
                call json_clear_exceptions()
            end if
        else
            ! grab the last child if present in the path
            if (child_i <= length) then
                nullify(tmp)
                call json_get_child(p, path(child_i:i-1), tmp)
                p => tmp
                nullify(tmp)
            end if
            if (associated(p)) then
                if (present(found)) found = .true.    !everything seems to be ok
            else
                call throw_exception('Error in json_get_by_path:'//&
                                     ' variable not found: '//trim(path))
                if (present(found)) then
                    found = .false.
                    call json_clear_exceptions()
                end if
            end if
        end if
    else
        if (present(found)) found = .false.
    end if
    end subroutine json_get_by_path
Call graph
json_get_by_path calls string_to_integer, json_clear_exceptions, json_get_child, throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars, to_unicode
to_unicode calls to_uni_vec, to_uni
wrap_json_throw_exception calls to_unicode, json_throw_exception
wrap_json_get_by_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get calls json_get_by_path, wrap_json_get_by_path, json_get_array_with_path, json_get_integer_with_path, json_get_double_with_path, json_get_string_with_path, json_get_logical_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_array_with_path, wrap_json_get_integer_with_path, wrap_json_get_double_with_path, wrap_json_get_string_with_path, wrap_json_get_logical_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
test_7 calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
test_2 calls json_get, json_update
json_file_get_string_vec calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
test_12 calls json_get, json_update
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
jf_test_12 calls test_12
wrap_json_get_array_with_path calls json_get_array_with_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path