json_update_string – JSON-Fortran
json_update_string Subroutine
Jacob Williams
12/6/2014
Source File
private subroutine json_update_string(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p_var
integer(kind=IK), public :: var_type
Source Code
    subroutine json_update_string(p,name,val,found)
    implicit none
    type(json_value),pointer            :: p
    character(kind=CK,len=*),intent(in) :: name
    character(kind=CK,len=*),intent(in) :: val
    logical(LK),intent(out)             :: found
    type(json_value),pointer :: p_var
    integer(IK) :: var_type
    call json_get(p,name,p_var,found)
    if (found) then
        call json_info(p_var,var_type)
        select case (var_type)
        case (json_null,json_logical,json_integer,json_double,json_string)
            call to_string(p_var,val)    !update the value
        case default
            found = .false.
            call throw_exception('Error in json_update_string: '//&
                                 'the variable is not a scalar value')
        end select
    else
        call json_add(p,name,val)   !add the new element
    end if
    end subroutine json_update_string
Call graph
json_update_string calls throw_exception, json_get, json_add, json_info, to_string
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_info calls json_count
to_string calls destroy_json_data
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls throw_exception, json_get_by_path, json_get_array, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls throw_exception, json_get_by_path, json_get_logical, json_clear_exceptions
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls throw_exception, json_get_by_path, json_get_string, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer calls throw_exception
json_get_integer_with_path calls throw_exception, json_get_by_path, json_get_integer, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls throw_exception, to_unicode
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, to_string, json_value_create, escape_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii
test_12 calls json_update
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
test_2 calls json_update
json_file_update_real calls json_update
jf_test_12 calls test_12
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
jf_test_2 calls test_2
wrap_json_file_update_real calls json_file_update_real