json_info – JSON-Fortran
json_info Subroutine
Jacob Williams
2/13/2014
Source File
public subroutine json_info(p, var_type, n_children, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
integer(kind=IK), intent(out), optional :: var_type
variable type
integer(kind=IK), intent(out), optional :: n_children
number of children
character(kind=CK,len=:), intent(out), optional allocatable :: name
variable name
Description
Returns information about a json_value.
Calls
Called By
Source Code
    subroutine json_info(p,var_type,n_children,name)
    implicit none
    type(json_value),pointer         :: p
    integer(IK),intent(out),optional :: var_type   !! variable type
    integer(IK),intent(out),optional :: n_children !! number of children
    character(kind=CK,len=:),allocatable,intent(out),optional :: name !! variable name
    if (present(var_type))    var_type   = p%var_type
    if (present(n_children))  n_children = json_count(p)
    if (present(name))        name       = p%name
    end subroutine json_info
Call graph
json_info calls json_count
json_update_string calls json_info
json_update_double calls json_info
json_update_logical calls json_info
json_update_integer calls json_info
test_2 calls json_info, json_update
json_file_variable_info calls json_info
rename calls json_info, json_update
test_10 calls json_info, json_update
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_double, json_update_logical, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_double, wrap_json_update_logical, wrap_json_update_integer
test_12 calls json_update
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
jf_test_12 calls test_12
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
wrap_json_update_logical calls json_update_logical
wrap_json_update_integer calls json_update_integer
jf_test_2 calls test_2
wrap_json_file_variable_info calls json_file_variable_info
jf_test_10 calls test_10