json_value_add_string_vec – JSON-Fortran
json_value_add_string_vec Subroutine
Jacob Williams
1/19/2014
Source File
private subroutine json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
variable name
character(kind=CK,len=*), intent(in), dimension(:) :: val
array of strings
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for each element
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for each element
Description
Add an array of character strings to the structure.
Note
This routine is part of the public API that can be used to build a JSON structure using json_value pointers.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: var
integer(kind=IK), public :: i
logical(kind=LK), public :: trim_string
logical(kind=LK), public :: adjustl_string
character(kind=CK,len=:), public, allocatable :: str
Source Code
    subroutine json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
    implicit none
    type(json_value),pointer                         :: me
    character(kind=CK,len=*),intent(in)              :: name        !! variable name
    character(kind=CK,len=*),dimension(:),intent(in) :: val         !! array of strings
    logical(LK),intent(in),optional                  :: trim_str    !! if TRIM() should be called for each element
    logical(LK),intent(in),optional                  :: adjustl_str !! if ADJUSTL() should be called for each element
    type(json_value),pointer :: var
    integer(IK) :: i
    logical(LK) :: trim_string, adjustl_string
    character(kind=CK,len=:),allocatable :: str
    !if the string is to be trimmed or not:
    if (present(trim_str)) then
        trim_string = trim_str
    else
        trim_string = .false.
    end if
    if (present(adjustl_str)) then
        adjustl_string = adjustl_str
    else
        adjustl_string = .false.
    end if
    !create the variable as an array:
    call json_value_create(var)
    call to_array(var,name)
    !populate the array:
    do i=1,size(val)
        !the string to write:
        str = val(i)
        if (adjustl_string) str = adjustl(str)
        if (trim_string)    str = trim(str)
        !write it:
        call json_add(var, '', str)
        !cleanup
        deallocate(str)
    end do
    !add it:
    call json_add(me, var)
    !cleanup:
    nullify(var)
    end subroutine json_value_add_string_vec
Call graph
json_value_add_string_vec calls json_add, json_value_create, to_array
json_add calls json_value_add_string_vec, json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
to_array calls destroy_json_data
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_unicode calls to_uni_vec, to_uni
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
parse_object calls json_add, parse_object, parse_value
parse_array calls json_add, parse_value
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_update_integer calls json_add
test_2 calls json_add, add_variables_to_input, json_update
test_12 calls json_add, json_update
test_7 calls json_add
test_4 calls json_add
add_variables_to_input calls json_add
parse_value calls parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_string, json_update_integer, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4