json_clear_exceptions – JSON-Fortran
json_clear_exceptions Subroutine
Jacob Williams
12/4/2013
Source File
public subroutine json_clear_exceptions()
Arguments
None
Description
Clear exceptions in the JSON module.
Called By
Source Code
    subroutine json_clear_exceptions()
    implicit none
    !clear the flag and message:
    exception_thrown = .false.
    err_message = ''
    end subroutine json_clear_exceptions
Call graph
json_get_array_with_path calls json_clear_exceptions, json_get_by_path
json_initialize calls json_clear_exceptions
json_get_integer_with_path calls json_clear_exceptions, json_get_by_path
json_get_double_with_path calls json_clear_exceptions, json_get_by_path
json_get_string_with_path calls json_clear_exceptions, json_get_by_path
json_print_error_message calls json_clear_exceptions
json_get_by_path calls json_clear_exceptions
json_get_logical_with_path calls json_clear_exceptions, json_get_by_path
wrap_json_get_array_with_path calls json_get_array_with_path
json_get calls json_get_array_with_path, json_get_integer_with_path, json_get_double_with_path, json_get_string_with_path, json_get_by_path, json_get_logical_with_path, wrap_json_get_array_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_integer_with_path, wrap_json_get_double_with_path, wrap_json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_logical_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
test_7 calls json_initialize, json_print_error_message, json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
test_2 calls json_initialize, json_print_error_message, json_get, json_update, add_variables_to_input
json_file_get_string_vec calls json_get
test_10 calls json_initialize, json_print_error_message, json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
test_12 calls json_initialize, json_get, json_update, check_errors
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_initialize, json_print_error_message, json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
jf_test_12 calls test_12
json_parse_file calls json_initialize
test_6 calls json_initialize, json_print_error_message
test_5 calls json_initialize, json_print_error_message
test_11 calls json_initialize, json_print_error_message
test_4 calls json_initialize, json_print_error_message
test_13 calls json_initialize, json_print_error_message
test_3 calls json_initialize, json_print_error_message
json_parse_string calls json_initialize
test_14 calls json_initialize, json_print_error_message, json_parse
test_9 calls json_initialize, json_print_error_message
test_8 calls json_initialize, json_print_error_message, json_parse
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
json_file_load_from_string calls json_parse
wrap_json_file_load_from_string calls json_file_load_from_string
jf_test_6 calls test_6
jf_test_5 calls test_5
jf_test_11 calls test_11
jf_test_4 calls test_4
jf_test_13 calls test_13
jf_test_3 calls test_3
wrap_json_parse_string calls json_parse_string
jf_test_14 calls test_14
jf_test_9 calls test_9
jf_test_8 calls test_8
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
add_variables_to_input calls json_print_error_message
wrap_json_get_by_path calls json_get_by_path
json_file_get_object calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_logical_with_path calls json_get_logical_with_path