json_get_string_vec_with_path – JSON-Fortran
json_get_string_vec_with_path Subroutine
Source File
private subroutine json_get_string_vec_with_path(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=*), intent(in) :: path
character(kind=CK,len=*), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Get a string vector from a json_file, given the path.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical(kind=LK), public :: initialized
Subroutines
subroutine get_chars_from_array(element, i, count)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: element
integer(kind=IK), intent(in) :: i
integer(kind=IK), intent(in) :: count
Source Code
    subroutine json_get_string_vec_with_path(me, path, vec, found)
    implicit none
    type(json_value),pointer,intent(in)                           :: me
    character(kind=CK,len=*),intent(in)                           :: path
    character(kind=CK,len=*),dimension(:),allocatable,intent(out) :: vec
    logical(LK),intent(out),optional                              :: found
    logical(LK) :: initialized
    initialized = .false.
    if (allocated(vec)) deallocate(vec)
    !the callback function is called for each element of the array:
    call json_get(me, path=path, array_callback=get_chars_from_array, found=found)
    contains
        ! callback function for chars
        subroutine get_chars_from_array(element, i, count)
        implicit none
        type(json_value),pointer,intent(in) :: element
        integer(IK),intent(in)              :: i        !index
        integer(IK),intent(in)              :: count    !size of array
        character(kind=CK,len=:),allocatable :: cval
        !size the output array:
        if (.not. initialized) then
            allocate(vec(count))
            initialized = .true.
        end if
        !populate the elements:
        call json_get(element, value=cval)
        if (allocated(cval)) then
            vec(i) = cval
            deallocate(cval)
        else
            vec(i) = ''
        end if
        end subroutine get_chars_from_array
    end subroutine json_get_string_vec_with_path
Call graph
json_get_string_vec_with_path calls json_get
json_get calls json_get_string_vec_with_path, json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path, to_unicode
json_get_double calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls json_get_double_with_path, to_unicode
json_get_double_vec calls json_get
json_get_array_with_path calls json_get_by_path, json_get_array, throw_exception, json_clear_exceptions
json_get_double_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path, to_unicode
json_get_logical calls throw_exception
json_get_logical_with_path calls json_get_by_path, json_get_logical, throw_exception, json_clear_exceptions
wrap_json_get_array_with_path calls json_get_array_with_path, to_unicode
wrap_json_get_logical_with_path calls json_get_logical_with_path, to_unicode
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path, to_unicode
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path, to_unicode
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls json_get_by_path, json_get_string, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls json_get_by_path, to_unicode
wrap_json_get_string_with_path calls json_get_string_with_path, to_unicode
json_get_integer calls throw_exception
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls json_get_integer_with_path, to_unicode
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
to_unicode calls to_uni_vec, to_uni
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls to_unicode, throw_exception
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
test_7 calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_file_get_integer calls json_get
test_2 calls json_get, json_update
json_file_get_string_vec calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_value_remove_if_present calls json_get
test_12 calls json_get, json_update
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
jf_test_12 calls test_12