json_value_create – JSON-Fortran
json_value_create Subroutine
Source File
private subroutine json_value_create(p)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
Description
Allocate a json_value pointer variable. This should be called before adding data to it.
Example
    type(json_value),pointer :: var
    call json_value_create(var)
    call to_double(var,1.0d0)
Notes
This routine does not check for exceptions.
The pointer should not already be allocated.
Called By
Source Code
    subroutine json_value_create(p)
    implicit none
    type(json_value),pointer :: p
    nullify(p)
    allocate(p)
    end subroutine json_value_create
Call graph
json_parse_file calls json_value_create, parse_value
json_value_create_object calls json_value_create
json_value_create_null calls json_value_create
json_value_add_integer_vec calls json_value_create, json_add
json_value_add_string_vec calls json_value_create, json_add
json_value_add_logical_vec calls json_value_create, json_add
json_parse_string calls json_value_create, parse_value
json_value_add_integer calls json_value_create, json_add
json_value_create_integer calls json_value_create
json_value_add_string calls json_value_create, json_add
json_value_add_double_vec calls json_value_create, json_add
parse_array calls json_value_create, json_add, parse_value
json_value_create_array calls json_value_create
json_value_add_double calls json_value_create, json_add
json_value_create_string calls json_value_create
json_value_add_logical calls json_value_create, json_add
parse_object calls json_value_create, parse_object, json_add, parse_value
json_value_create_logical calls json_value_create
json_value_create_double calls json_value_create
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_value_create_object calls json_value_create_object
json_create_object calls json_value_create_object, wrap_json_value_create_object
test_7 calls json_create_object, json_add, json_create_array
test_2 calls json_create_object, add_variables_to_input, json_add, json_update, json_create_array
add_variables_to_input calls json_create_object, json_add
test_12 calls json_create_object, json_add, json_update
test_10 calls json_create_object, json_create_null, json_update, json_create_integer, json_create_string, json_create_logical, json_create_double
test_4 calls json_create_object, json_add
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_10 calls test_10
jf_test_4 calls test_4
wrap_json_value_create_null calls json_value_create_null
json_create_null calls json_value_create_null, wrap_json_value_create_null
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
json_add calls json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_integer, json_value_add_string, json_value_add_double_vec, json_value_add_double, json_value_add_logical, wrap_json_value_add_integer_vec, json_value_add_string_vec_name_ascii, wrap_json_value_add_string_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, json_value_add_string_name_ascii, wrap_json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_double_vec, wrap_json_value_add_double, wrap_json_value_add_logical
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_update_integer calls json_add
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_string, json_update_integer, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
wrap_json_parse_string calls json_parse_string
wrap_json_value_add_integer calls json_value_add_integer
wrap_json_value_create_integer calls json_value_create_integer
json_create_integer calls json_value_create_integer, wrap_json_value_create_integer
json_value_add_string_name_ascii calls json_value_add_string
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
wrap_json_value_add_double_vec calls json_value_add_double_vec
parse_value calls parse_array, parse_object
wrap_json_value_create_array calls json_value_create_array
json_create_array calls json_value_create_array, wrap_json_value_create_array
wrap_json_value_add_double calls json_value_add_double
wrap_json_value_create_string calls json_value_create_string
json_create_string calls json_value_create_string, wrap_json_value_create_string
wrap_json_value_add_logical calls json_value_add_logical
wrap_json_value_create_logical calls json_value_create_logical
json_create_logical calls json_value_create_logical, wrap_json_value_create_logical
wrap_json_value_create_double calls json_value_create_double
json_create_double calls json_value_create_double, wrap_json_value_create_double