json_value_remove_if_present – JSON-Fortran
json_value_remove_if_present Subroutine
Jacob Williams
12/6/2014
Source File
private subroutine json_value_remove_if_present(p, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
Description
Given the path string, remove the variable from the json_value structure, if it exists.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p_var
logical(kind=LK), public :: found
Source Code
    subroutine json_value_remove_if_present(p,name)
    implicit none
    type(json_value),pointer            :: p
    character(kind=CK,len=*),intent(in) :: name
    type(json_value),pointer :: p_var
    logical(LK) :: found
    call json_get(p,name,p_var,found)
    if (found) call json_remove(p_var)
    end subroutine json_value_remove_if_present
Call graph
json_value_remove_if_present calls json_get, json_remove
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_remove calls json_value_remove
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path, to_unicode
json_get_double calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls json_get_double_with_path, to_unicode
json_get_double_vec calls json_get
json_get_array_with_path calls json_get_by_path, json_get_array, throw_exception, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path, to_unicode
json_get_logical calls throw_exception
json_get_logical_with_path calls json_get_by_path, json_get_logical, throw_exception, json_clear_exceptions
wrap_json_get_array_with_path calls json_get_array_with_path, to_unicode
wrap_json_get_logical_with_path calls json_get_logical_with_path, to_unicode
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path, to_unicode
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path, to_unicode
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls json_get_by_path, json_get_string, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls json_get_by_path, to_unicode
wrap_json_get_string_with_path calls json_get_string_with_path, to_unicode
json_get_integer calls throw_exception
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls json_get_integer_with_path, to_unicode
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
to_unicode calls to_uni_vec, to_uni
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls to_unicode, throw_exception
json_value_remove calls json_value_destroy
json_value_destroy calls json_value_destroy, destroy_json_data
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
test_10 calls json_remove_if_present
jf_test_10 calls test_10