json_get_integer – JSON-Fortran
json_get_integer Subroutine
Source File
private subroutine json_get_integer(me, value)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
integer(kind=IK), intent(out) :: value
Description
Get an integer value from a json_value.
Calls
Called By
Source Code
    subroutine json_get_integer(me, value)
    implicit none
    type(json_value),pointer,intent(in) :: me
    integer(IK),intent(out)             :: value
    value = 0
    if ( exception_thrown ) return
    select case(me%var_type)
    case (json_integer)
        value = me%int_value
    case (json_double)
        value = int(me%dbl_value)
    case (json_logical)
        if (me%log_value) then
            value = 1
        else
            value = 0
        end if
    case default
        call throw_exception('Error in get_integer:'//&
             ' Unable to resolve value to integer: '//me%name)
    end select
    end subroutine json_get_integer
Call graph
json_get_integer calls throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_get_integer_with_path calls json_get_integer
wrap_json_get_integer_with_path calls json_get_integer_with_path
json_get calls json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
test_7 calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
test_2 calls json_get, json_update
json_file_get_string_vec calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
test_12 calls json_get, json_update
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
jf_test_12 calls test_12