json_count – JSON-Fortran
json_count Function
Source File
public pure function json_count(me) result(count)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
Return Value integer(kind=IK)
number of children
Description
Count the number of children.
History
JW : 1/4/2014 : Original routine removed. Now using n_children variable. Renamed from json_value_count.
Called By
Source Code
    pure function json_count(me) result(count)
    implicit none
    integer(IK)                         :: count  !! number of children
    type(json_value),pointer,intent(in) :: me
    count = me%n_children
    end function json_count
Call graph
json_value_print calls json_count, json_value_print
json_traverse calls json_count, json_traverse
json_get_array calls json_count
json_info calls json_count
json_value_get_by_name_chars calls json_count
json_print_1 calls json_value_print
json_value_to_string calls json_value_print
json_file_print_1 calls json_value_print
json_file_print_to_console calls json_value_print
json_print calls json_print_1, json_print_2
json_print_2 calls json_print
test_2 calls json_info, json_print, json_get, json_update
test_14 calls json_traverse, json_print
test_12 calls json_print, json_get, json_update
test_7 calls json_print, json_get, json_get_child
test_4 calls json_print, json_print_to_string
test_8 calls json_print
jf_test_2 calls test_2
jf_test_14 calls test_14
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4
jf_test_8 calls test_8
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string
json_get_array_with_path calls json_get_array, json_get_by_path
wrap_json_get_array_with_path calls json_get_array_with_path
json_get calls json_get_array, json_get_array_with_path, wrap_json_get_array_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, json_get_by_path, wrap_json_get_by_path, json_get_integer_with_path, json_get_double_with_path, json_get_string_with_path, json_get_logical_with_path, wrap_json_get_integer_with_path, wrap_json_get_double_with_path, wrap_json_get_string_with_path, wrap_json_get_logical_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_info, json_get
rename calls json_info, json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_info, json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_info, json_get
json_get_double_vec_with_path calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_info, json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
json_file_get_string_vec calls json_get
test_10 calls json_info, json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
json_file_variable_info calls json_info
wrap_json_file_variable_info calls json_file_variable_info
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars
json_get_child calls json_value_get_by_name_chars, wrap_json_value_get_by_name_chars
json_get_by_path calls json_get_child
wrap_json_get_by_path calls json_get_by_path
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path