json_file_print_to_console – JSON-Fortran
json_file_print_to_console Subroutine
Jacob Williams
1/11/2015
Source File
private subroutine json_file_print_to_console(me)
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
Description
Print the JSON file to the console.
Calls
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=:), public, allocatable :: dummy
Source Code
    subroutine json_file_print_to_console(me)
    implicit none
    class(json_file),intent(inout)  :: me
    character(kind=CK,len=:),allocatable :: dummy
    call json_value_print(me%p,iunit=output_unit,str=dummy,indent=1,colon=.true.)
    end subroutine json_file_print_to_console
Call graph
json_file_print_to_console calls json_value_print
json_value_print calls json_value_print, json_count, throw_exception, write_it, real_to_string, integer_to_string
throw_exception calls json_throw_exception, wrap_json_throw_exception
real_to_string calls compact_real_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni