json_value_get_by_index – JSON-Fortran
json_value_get_by_index Subroutine
Source File
private subroutine json_value_get_by_index(me, idx, p)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
object or array JSON data
integer(kind=IK), intent(in) :: idx
index of the child
type(json_value), , pointer :: p
pointer to the child
Description
Returns a child in the object or array given the index.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
Source Code
    subroutine json_value_get_by_index(me, idx, p)
    implicit none
    type(json_value),pointer,intent(in) :: me   !! object or array JSON data
    integer(IK),intent(in)              :: idx  !! index of the child
    type(json_value),pointer            :: p    !! pointer to the child
    integer(IK) :: i
    nullify(p)
    if (.not. exception_thrown) then
        if (associated(me%children)) then
            p => me%children
            do i = 1, idx - 1
                if (associated(p%next)) then
                    p => p%next
                else
                    call throw_exception('Error in json_value_get_by_index:'//&
                                         ' p%next is not associated.')
                    nullify(p)
                    return
                end if
            end do
        else
            call throw_exception('Error in json_value_get_by_index:'//&
                                 ' me%children is not associated.')
        end if
    end if
    end subroutine json_value_get_by_index
Call graph
json_value_get_by_index calls throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_get_child calls json_value_get_by_index
json_get_by_path calls json_get_child
test_7 calls json_get_child, json_get
wrap_json_get_by_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get calls json_get_by_path, wrap_json_get_by_path, json_get_array_with_path, json_get_integer_with_path, json_get_double_with_path, json_get_string_with_path, json_get_logical_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_array_with_path, wrap_json_get_integer_with_path, wrap_json_get_double_with_path, wrap_json_get_string_with_path, wrap_json_get_logical_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
test_2 calls json_get, json_update
json_file_get_string_vec calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
test_12 calls json_get, json_update
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
jf_test_12 calls test_12
wrap_json_get_array_with_path calls json_get_array_with_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path
jf_test_7 calls test_7