json_file_get_object – JSON-Fortran
json_file_get_object Subroutine
Jacob Williams
2/3/2014
Source File
private subroutine json_file_get_object(me, path, p, found)
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CK,len=*), intent(in) :: path
the path to the variable
type(json_value), intent(out), pointer :: p
pointer to the variable
logical(kind=LK), intent(out), optional :: found
if it was really found
Description
Get a json_value pointer to an object from a JSON file.
Calls
Called By
Source Code
    subroutine json_file_get_object(me, path, p, found)
    implicit none
    class(json_file),intent(inout)       :: me
    character(kind=CK,len=*),intent(in)  :: path   !! the path to the variable
    type(json_value),pointer,intent(out) :: p      !! pointer to the variable
    logical(LK),intent(out),optional     :: found  !! if it was really found
    call json_get_by_path(me%p, path=path, p=p, found=found)
    end subroutine json_file_get_object
Call graph
json_file_get_object calls json_get_by_path
json_get_by_path calls string_to_integer, json_clear_exceptions, json_get_child, throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls json_value_get_by_name_chars, to_unicode
to_unicode calls to_uni_vec, to_uni
wrap_json_throw_exception calls to_unicode, json_throw_exception
wrap_json_file_get_object calls json_file_get_object