json_value_add_member – JSON-Fortran
json_value_add_member Subroutine
Source File
private subroutine json_value_add_member(me, member)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
type(json_value), , pointer :: member
the child member to add
Description
Adds "member" as a child of "me".
Called By
Source Code
    subroutine json_value_add_member(me, member)
    implicit none
    type(json_value),pointer :: me
    type(json_value),pointer :: member  !! the child member to add
    if (.not. exception_thrown) then
        ! associate the parent
        member%parent => me
        ! add to linked list
        if (associated(me%children)) then
            me%tail%next => member
            member%previous => me%tail
        else
            me%children => member
            member%previous => null()  !first in the list
        end if
        ! new member is now the last one in the list
        me%tail => member
        me%n_children = me%n_children + 1
    end if
    end subroutine json_value_add_member
Call graph
json_add calls json_value_add_member, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_integer, json_value_add_double_vec, json_value_add_double, json_value_add_string, json_value_add_logical, wrap_json_value_add_integer_vec, json_value_add_string_vec_name_ascii, wrap_json_value_add_string_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical_vec, wrap_json_value_add_integer, wrap_json_value_add_double_vec, wrap_json_value_add_double, json_value_add_string_name_ascii, wrap_json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_logical
parse_object calls json_add, parse_object, parse_value
parse_array calls json_add, parse_value
json_value_add_integer_vec calls json_add
json_value_add_string_vec calls json_add
json_value_add_logical_vec calls json_add
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_update_integer calls json_add
json_value_add_integer calls json_add
test_2 calls json_add, add_variables_to_input, json_update
json_value_add_double_vec calls json_add
test_12 calls json_add, json_update
json_value_add_double calls json_add
test_7 calls json_add
json_value_add_string calls json_add
json_value_add_logical calls json_add
test_4 calls json_add
add_variables_to_input calls json_add
parse_value calls parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_string, json_update_integer, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
wrap_json_value_add_integer calls json_value_add_integer
jf_test_2 calls test_2
wrap_json_value_add_double_vec calls json_value_add_double_vec
jf_test_12 calls test_12
wrap_json_value_add_double calls json_value_add_double
jf_test_7 calls test_7
json_value_add_string_name_ascii calls json_value_add_string
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
wrap_json_value_add_logical calls json_value_add_logical
jf_test_4 calls test_4