json_print_2 – JSON-Fortran
json_print_2 Subroutine
Jacob Williams
12/23/2014
Source File
private subroutine json_print_2(me, filename)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CDK,len=*), intent(in) :: filename
the filename to print to (should not already be open)
Description
Print the json_value structure to a file.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: iunit
integer(kind=IK), public :: istat
Source Code
    subroutine json_print_2(me,filename)
    implicit none
    type(json_value),pointer,intent(in)  :: me
    character(kind=CDK,len=*),intent(in) :: filename  !! the filename to print to (should not already be open)
    integer(IK) :: iunit,istat
    open(newunit=iunit,file=filename,status='REPLACE',iostat=istat FILE_ENCODING )
    if (istat==0) then
        call json_print(me,iunit)
        close(iunit,iostat=istat)
    else
        call throw_exception('Error in json_print: could not open file: '//&
                              trim(filename))
    end if
    end subroutine json_print_2
Call graph
json_print_2 calls json_print, throw_exception
json_print calls json_print_2, json_print_1
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_print_1 calls throw_exception, json_value_print
json_value_print calls throw_exception, json_value_print, json_count, write_it, real_to_string, integer_to_string
real_to_string calls compact_real_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
test_2 calls json_print
test_14 calls json_print
test_12 calls json_print
test_7 calls json_print
test_4 calls json_print
test_8 calls json_print
jf_test_2 calls test_2
jf_test_14 calls test_14
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4
jf_test_8 calls test_8