json_value_to_string – JSON-Fortran
json_value_to_string Subroutine
Jacob Williams
2/12/2014
Source File
private subroutine json_value_to_string(me, str)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: me
character(kind=CK,len=:), intent(out), allocatable :: str
prints structure to this string
Description
Print the json_value structure to an allocatable string.
Calls
Called By
Source Code
    subroutine json_value_to_string(me,str)
    implicit none
    type(json_value),pointer,intent(in)              :: me
    character(kind=CK,len=:),intent(out),allocatable :: str  !! prints structure to this string
    str = ''
    call json_value_print(me, iunit=unit2str, str=str, indent=1, colon=.true.)
    end subroutine json_value_to_string
Call graph
json_value_to_string calls json_value_print
json_value_print calls json_value_print, json_count, throw_exception, write_it, real_to_string, integer_to_string
throw_exception calls json_throw_exception, wrap_json_throw_exception
real_to_string calls compact_real_string
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string
test_4 calls json_print_to_string
jf_test_4 calls test_4