json_file_update_string – JSON-Fortran
json_file_update_string Subroutine
Jacob Williams
1/10/2015
Source File
private subroutine json_file_update_string(me, name, val, found)
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Given the path string, if the variable is present in the file, and is a scalar, then update its value. If it is not present, then create it and set its value.
See also
json_update_string
Calls
Called By
Source Code
    subroutine json_file_update_string(me,name,val,found)
    implicit none
    class(json_file),intent(inout)      :: me
    character(kind=CK,len=*),intent(in) :: name
    character(kind=CK,len=*),intent(in) :: val
    logical(LK),intent(out)             :: found
    if (.not. exception_thrown) call json_update(me%p,name,val,found)
    end subroutine json_file_update_string
Call graph
json_file_update_string calls json_update
json_update calls json_update_double, json_update_logical, json_update_string, wrap_json_update_double, wrap_json_update_integer, json_update_integer, wrap_json_update_string, json_update_string_val_ascii, json_update_string_name_ascii, wrap_json_update_logical
json_update_double calls throw_exception, json_get, json_add, json_info, to_double
json_update_logical calls throw_exception, json_get, json_add, json_info, to_logical
json_update_string calls throw_exception, json_get, json_add, json_info, to_string
wrap_json_update_double calls json_update_double, to_unicode
wrap_json_update_integer calls json_update_integer, to_unicode
json_update_integer calls throw_exception, json_get, json_add, json_info, to_integer
wrap_json_update_string calls json_update_string, to_unicode
json_update_string_val_ascii calls json_update_string, to_unicode
json_update_string_name_ascii calls json_update_string, to_unicode
wrap_json_update_logical calls json_update_logical, to_unicode
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_info calls json_count
to_double calls destroy_json_data
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls throw_exception, json_get_by_path, json_get_array, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls throw_exception, json_get_by_path, json_get_logical, json_clear_exceptions
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls throw_exception, json_get_by_path, json_get_string, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer calls throw_exception
json_get_integer_with_path calls throw_exception, json_get_by_path, json_get_integer, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls throw_exception, to_unicode
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, to_double, json_value_create
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string