parse_string – JSON-Fortran
parse_string Subroutine
Source File
private subroutine parse_string(unit, str, string)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK,len=*), intent(in) :: str
JSON string (if parsing from a string)
character(kind=CK,len=:), intent(out), allocatable :: string
Description
Parses a string while reading a JSON file.
History
Jacob Williams : 6/16/2014 : Added hex validation.
Jacob Williams : 12/3/2015 : Fixed some bugs.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical(kind=LK), public :: eof
logical(kind=LK), public :: is_hex
logical(kind=LK), public :: escape
character(kind=CK,len=1), public :: c
character(kind=CK,len=4), public :: hex
integer(kind=IK), public :: i
integer(kind=IK), public :: ip
index to put next character, to speed up by reducing the number of character string reallocations.
Source Code
    subroutine parse_string(unit, str, string)
    implicit none
    integer(IK),intent(in)                           :: unit  !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in)              :: str   !! JSON string (if parsing from a string)
    character(kind=CK,len=:),allocatable,intent(out) :: string
    logical(LK) :: eof, is_hex, escape
    character(kind=CK,len=1) :: c
    character(kind=CK,len=4) :: hex
    integer(IK) :: i
    integer(IK) :: ip !! index to put next character,
                      !! to speed up by reducing the number of character string reallocations.
    !at least return a blank string if there is a problem:
    string = repeat(space, chunk_size)
    if (.not. exception_thrown) then
        !initialize:
        ip     = 1
        is_hex = .false.
        escape = .false.
        i      = 0
        do
            !get the next character from the file:
            c = pop_char(unit, str=str, eof = eof, skip_ws = .false.)
            if (eof) then
                call throw_exception('Error in parse_string: Expecting end of string')
                return
            else if (c==quotation_mark .and. .not. escape) then  !end of string
                if (is_hex) call throw_exception('Error in parse_string:'//&
                                                 ' incomplete hex string: \u'//trim(hex))
                exit
            else
                !if the string is not big enough, then add another chunk:
                if (ip>len(string)) string = string // repeat(space, chunk_size)
                !append to string:
                string(ip:ip) = c
                ip = ip + 1
                !hex validation:
                if (is_hex) then  !accumulate the four characters after '\u'
                    i=i+1
                    hex(i:i) = c
                    if (i==4) then
                        if (valid_json_hex(hex)) then
                            i = 0
                            hex = ''
                            is_hex = .false.
                        else
                            call throw_exception('Error in parse_string:'//&
                                                 ' invalid hex string: \u'//trim(hex))
                            exit
                        end if
                    end if
                else
                    !when the '\u' string is encountered, then
                    !  start accumulating the hex string (should be the next 4 characters)
                    if (escape) then
                        escape = .false.
                        is_hex = (c=='u')    !the next four characters are the hex string
                    else
                        escape = (c==backslash)
                    end if
                end if
            end if
        end do
        !trim the string if necessary:
        if (ip<len(string)+1) then
            if (ip==1) then
                string = ''
            else
                string = string(1:ip-1)
            end if
        end if
    end if
    end subroutine parse_string
Call graph
parse_string calls valid_json_hex, pop_char, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
parse_object calls parse_string, parse_object, parse_value
parse_value calls parse_string, parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string