parse_for_chars – JSON-Fortran
parse_for_chars Subroutine
Source File
private subroutine parse_for_chars(unit, str, chars)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK,len=*), intent(in) :: str
JSON string (if parsing from a string)
character(kind=CK,len=*), intent(in) :: chars
the string to check for.
Description
Core parsing routine.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: i
integer(kind=IK), public :: length
logical(kind=LK), public :: eof
character(kind=CK,len=1), public :: c
Source Code
    subroutine parse_for_chars(unit, str, chars)
    implicit none
    integer(IK),intent(in)              :: unit   !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str    !! JSON string (if parsing from a string)
    character(kind=CK,len=*),intent(in) :: chars  !! the string to check for.
    integer(IK) :: i, length
    logical(LK) :: eof
    character(kind=CK,len=1) :: c
    if (.not. exception_thrown) then
        length = len_trim(chars)
        do i = 1, length
            c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
            if (eof) then
                call throw_exception('Error in parse_for_chars:'//&
                                     ' Unexpected end of file while parsing array.')
                return
            else if (c /= chars(i:i)) then
                call throw_exception('Error in parse_for_chars:'//&
                                     ' Unexpected character.: "'//c//'" '//chars(i:i))
                return
            end if
        end do
    end if
    end subroutine parse_for_chars
Call graph
parse_for_chars calls pop_char, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
parse_value calls parse_for_chars, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string