parse_array – JSON-Fortran
parse_array Subroutine
Source File
private recursive subroutine parse_array(unit, str, array)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK,len=*), intent(in) :: str
JSON string (if parsing from a string)
type(json_value), , pointer :: array
Description
Core parsing routine.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: element
logical(kind=LK), public :: eof
character(kind=CK,len=1), public :: c
Source Code
    recursive subroutine parse_array(unit, str, array)
    implicit none
    integer(IK),intent(in)              :: unit   !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str    !! JSON string (if parsing from a string)
    type(json_value),pointer            :: array
    type(json_value),pointer :: element
    logical(LK) :: eof
    character(kind=CK,len=1) :: c
    do
        if (exception_thrown) exit
        ! try to parse an element value
        nullify(element)
        call json_value_create(element)
        call parse_value(unit, str, element)
        if (exception_thrown) then
            if (associated(element)) call json_destroy(element)
            exit
        end if
        ! parse value will disassociate an empty array value
        if (associated(element)) call json_add(array, element)
        ! popped the next character
        c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
        if (eof) then
            ! The file ended before array was finished:
            call throw_exception('Error in parse_array: '//&
                                 'End of file encountered when parsing an array.')
            exit
        else if (delimiter == c) then
            ! parse the next element
            cycle
        else if (end_array == c) then
            ! end of array
            exit
        else
            call throw_exception('Error in parse_array: '//&
                                 'Unexpected character encountered when parsing array.')
            exit
        end if
    end do
    end subroutine parse_array
Call graph
parse_array calls pop_char, throw_exception, parse_value, json_destroy, json_add, json_value_create
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_value calls parse_array, pop_char, throw_exception, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object
json_destroy calls json_value_destroy
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls pop_char, throw_exception, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls pop_char, throw_exception
parse_number calls pop_char, throw_exception, push_char, string_to_integer, to_double, string_to_double, to_integer
parse_object calls pop_char, throw_exception, parse_value, json_destroy, json_add, json_value_create, parse_string, parse_object
string_to_integer calls throw_exception
to_double calls destroy_json_data
string_to_double calls throw_exception
to_integer calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, json_value_create, to_string, escape_string
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string