parse_value – JSON-Fortran
parse_value Subroutine
Source File
private recursive subroutine parse_value(unit, str, value)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number
character(kind=CK,len=*), intent(in) :: str
string containing JSON data (only used if unit=0)
type(json_value), , pointer :: value
JSON data that is extracted
Description
Core parsing routine.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical(kind=LK), public :: eof
character(kind=CK,len=1), public :: c
character(kind=CK,len=:), public, allocatable :: tmp
Source Code
    recursive subroutine parse_value(unit, str, value)
    implicit none
    integer(IK),intent(in)              :: unit   !! file unit number
    character(kind=CK,len=*),intent(in) :: str    !! string containing JSON data (only used if unit=0)
    type(json_value),pointer            :: value  !! JSON data that is extracted
    logical(LK) :: eof
    character(kind=CK,len=1) :: c
    character(kind=CK,len=:),allocatable :: tmp  !this is a work-around for a bug
                                                 ! in the gfortran 4.9 compiler.
    if (.not. exception_thrown) then
        !the routine is being called incorrectly.
        if (.not. associated(value)) then
            call throw_exception('Error in parse_value: value pointer not associated.')
        end if
        ! pop the next non whitespace character off the file
        c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
        if (eof) then
            return
        else
            select case (c)
            case (start_object)
                ! start object
                call to_object(value)    !allocate class
                call parse_object(unit, str, value)
            case (start_array)
                ! start array
                call to_array(value)    !allocate class
                call parse_array(unit, str, value)
            case (end_array)
                ! end an empty array
                call push_char(c)
                nullify(value)
            case (quotation_mark)
                ! string
                call to_string(value)    !allocate class
                select case (value%var_type)
                case (json_string)
                    call parse_string(unit, str, tmp)  !write to a tmp variable because of
                    value%str_value = tmp              ! a bug in 4.9 gfortran compiler.
                    deallocate(tmp)                    !
                end select
            case (CK_'t') !true_str(1:1) gfortran bug work around
                !true
                call parse_for_chars(unit, str, true_str(2:))
                !allocate class and set value:
                if (.not. exception_thrown) call to_logical(value,.true.)
            case (CK_'f') !false_str(1:1) gfortran bug work around
                !false
                call parse_for_chars(unit, str, false_str(2:))
                !allocate class and set value:
                if (.not. exception_thrown) call to_logical(value,.false.)
            case (CK_'n') !null_str(1:1) gfortran bug work around
                !null
                call parse_for_chars(unit, str, null_str(2:))
                if (.not. exception_thrown) call to_null(value)    !allocate class
            case(CK_'-', CK_'0': CK_'9')
                call push_char(c)
                call parse_number(unit, str, value)
            case default
                call throw_exception('Error in parse_value:'//&
                                     ' Unexpected character while parsing value. "'//&
                                     c//'"')
            end select
        end if
    end if
    end subroutine parse_value
Call graph
parse_value calls parse_array, throw_exception, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object, pop_char
parse_array calls parse_value, throw_exception, pop_char, json_destroy, json_add, json_value_create
throw_exception calls json_throw_exception, wrap_json_throw_exception
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, push_char, pop_char, to_integer, to_double, string_to_integer, string_to_double
parse_object calls parse_value, throw_exception, parse_string, parse_object, pop_char, json_destroy, json_add, json_value_create
json_destroy calls json_value_destroy
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_destroy calls json_value_destroy, destroy_json_data
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls to_array, json_add, json_value_create
json_value_add_string_vec calls to_array, json_add, json_value_create
json_value_add_logical_vec calls to_array, json_add, json_value_create
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls to_array, json_add, json_value_create
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls to_logical, json_add, json_value_create
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls to_string, json_add, json_value_create, escape_string
to_unicode calls to_uni_vec, to_uni
to_integer calls destroy_json_data
to_double calls destroy_json_data
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
string_to_double calls throw_exception
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string