parse_object – JSON-Fortran
parse_object Subroutine
Source File
private recursive subroutine parse_object(unit, str, parent)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK,len=*), intent(in) :: str
JSON string (if parsing from a string)
type(json_value), , pointer :: parent
the parsed object will be added as a child of this
Description
Core parsing routine.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: pair
logical(kind=LK), public :: eof
character(kind=CK,len=1), public :: c
character(kind=CK,len=:), public, allocatable :: tmp
this is a work-around for a bug in the gfortran 4.9 compiler.
Source Code
    recursive subroutine parse_object(unit, str, parent)
    implicit none
    integer(IK),intent(in)              :: unit    !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str     !! JSON string (if parsing from a string)
    type(json_value),pointer            :: parent  !! the parsed object will be added as a child of this
    type(json_value),pointer :: pair
    logical(LK) :: eof
    character(kind=CK,len=1) :: c
    character(kind=CK,len=:),allocatable :: tmp  !! this is a work-around for a bug
                                                 !! in the gfortran 4.9 compiler.
    if (.not. exception_thrown) then
        !the routine is being called incorrectly.
        if (.not. associated(parent)) then
            call throw_exception('Error in parse_object: parent pointer not associated.')
        end if
        nullify(pair)    !probably not necessary
        ! pair name
        c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
        if (eof) then
            call throw_exception('Error in parse_object:'//&
                                 ' Unexpected end of file while parsing start of object.')
            return
        else if (end_object == c) then
            ! end of an empty object
            return
        else if (quotation_mark == c) then
            call json_value_create(pair)
            call parse_string(unit, str, tmp)   !write to a tmp variable because of
            pair % name = tmp                   ! a bug in 4.9 gfortran compiler.
            deallocate(tmp)
            if (exception_thrown) then
                call json_destroy(pair)
                return
            end if
        else
            call throw_exception('Error in parse_object: Expecting string: "'//c//'"')
            return
        end if
        ! pair value
        c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
        if (eof) then
            call throw_exception('Error in parse_object:'//&
                                 ' Unexpected end of file while parsing object member.')
            return
        else if (colon_char == c) then
            ! parse the value
            call parse_value(unit, str, pair)
            if (exception_thrown) then
                call json_destroy(pair)
                return
            else
                call json_add(parent, pair)
            end if
        else
            call throw_exception('Error in parse_object:'//&
                                 ' Expecting : and then a value: '//c)
            return
        end if
        ! another possible pair
        c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
        if (eof) then
            call throw_exception('Error in parse_object: '//&
                                 'End of file encountered when parsing an object')
            return
        else if (delimiter == c) then
            ! read the next member
            call parse_object(unit = unit, str=str, parent = parent)
        else if (end_object == c) then
            ! end of object
            return
        else
            call throw_exception('Error in parse_object: Expecting end of object: '//c)
            return
        end if
    end if
    end subroutine parse_object
Call graph
parse_object calls parse_object, throw_exception, pop_char, parse_string, json_add, json_destroy, json_value_create, parse_value
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_string calls throw_exception, pop_char, valid_json_hex
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_destroy calls json_value_destroy
parse_value calls parse_object, throw_exception, pop_char, parse_string, to_array, to_logical, to_string, parse_array, push_char, to_null, to_object, parse_for_chars, parse_number
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
json_value_destroy calls destroy_json_data, json_value_destroy
parse_array calls throw_exception, pop_char, json_add, json_destroy, json_value_create, parse_value
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, pop_char, to_integer, to_double, push_char, string_to_integer, string_to_double
string_to_integer calls throw_exception
string_to_double calls throw_exception
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string