parse_number – JSON-Fortran
parse_number Subroutine
Jacob Williams
1/20/2014
Source File
private subroutine parse_number(unit, str, value)
Arguments
Type Intent Optional Attributes Name
integer(kind=IK), intent(in) :: unit
file unit number (if parsing from a file)
character(kind=CK,len=*), intent(in) :: str
JSON string (if parsing from a string)
type(json_value), , pointer :: value
Description
Read a numerical value from the file (or string). The routine will determine if it is an integer or a double, and allocate the type accordingly.
Note
Complete rewrite of the original FSON routine, which had some problems.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=:), public, allocatable :: tmp
character(kind=CK,len=1), public :: c
logical(kind=LK), public :: eof
real(kind=RK), public :: rval
integer(kind=IK), public :: ival
logical(kind=LK), public :: first
logical(kind=LK), public :: is_integer
integer(kind=IK), public :: ip
Source Code
    subroutine parse_number(unit, str, value)
    implicit none
    integer(IK),intent(in)              :: unit   !! file unit number (if parsing from a file)
    character(kind=CK,len=*),intent(in) :: str    !! JSON string (if parsing from a string)
    type(json_value),pointer            :: value
    character(kind=CK,len=:),allocatable :: tmp
    character(kind=CK,len=1) :: c
    logical(LK) :: eof
    real(RK) :: rval
    integer(IK) :: ival
    logical(LK) :: first
    logical(LK) :: is_integer
    !to speed up by reducing the number of character string reallocations:
    integer(IK) :: ip !index to put next character
    if (.not. exception_thrown) then
        tmp = repeat(space, chunk_size)
        ip = 1
        first = .true.
        is_integer = .true.  !assume it may be an integer, unless otherwise determined
        !read one character at a time and accumulate the string:
        do
            !get the next character:
            c = pop_char(unit, str=str, eof = eof, skip_ws = .true.)
            if (eof) then
                call throw_exception('Error in parse_number:'//&
                                     ' Unexpected end of file while parsing number.')
                return
            else
                select case (c)
                case(CK_'-',CK_'+')    !note: allowing a '+' as the first character here.
                    if (is_integer .and. (.not. first)) is_integer = .false.
                    !add it to the string:
                    !tmp = tmp // c   !...original
                    if (ip>len(tmp)) tmp = tmp // repeat(space, chunk_size)
                    tmp(ip:ip) = c
                    ip = ip + 1
                case(CK_'.',CK_'E',CK_'e')    !can be present in real numbers
                    if (is_integer) is_integer = .false.
                    !add it to the string:
                    !tmp = tmp // c   !...original
                    if (ip>len(tmp)) tmp = tmp // repeat(space, chunk_size)
                    tmp(ip:ip) = c
                    ip = ip + 1
                case(CK_'0':CK_'9')    !valid characters for numbers
                    !add it to the string:
                    !tmp = tmp // c   !...original
                    if (ip>len(tmp)) tmp = tmp // repeat(space, chunk_size)
                    tmp(ip:ip) = c
                    ip = ip + 1
                case default
                    !push back the last character read:
                    call push_char(c)
                    !string to value:
                    if (is_integer) then
                        ival = string_to_integer(tmp)
                        call to_integer(value,ival)
                    else
                        rval = string_to_double(tmp)
                        call to_double(value,rval)
                    end if
                    exit    !finished
                end select
            end if
            if (first) first = .false.
        end do
        !cleanup:
        if (allocated(tmp)) deallocate(tmp)
    end if
    end subroutine parse_number
Call graph
parse_number calls throw_exception, string_to_integer, to_double, string_to_double, push_char, to_integer, pop_char
throw_exception calls json_throw_exception, wrap_json_throw_exception
string_to_integer calls throw_exception
to_double calls destroy_json_data
string_to_double calls throw_exception
push_char calls throw_exception, integer_to_string
to_integer calls destroy_json_data
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
parse_value calls parse_number, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string