push_char – JSON-Fortran
push_char Subroutine
Source File
private subroutine push_char(c)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=1), intent(in) :: c
Description
Core routine.
See also
pop_char
History
Jacob Williams : 5/3/2015 : replaced original version of this routine.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=max_numeric_str_len), public :: istr
Source Code
    subroutine push_char(c)
    implicit none
    character(kind=CK,len=1),intent(in) :: c
    character(kind=CK,len=max_numeric_str_len) :: istr
    if (.not. exception_thrown) then
        if (use_unformatted_stream) then
            !in this case, c is ignored, and we just
            !decrement the stream position counter:
            ipos = ipos - 1
        else
            pushed_index = pushed_index + 1
            if (pushed_index>0 .and. pushed_index<=len(pushed_char)) then
                pushed_char(pushed_index:pushed_index) = c
            else
                call integer_to_string(pushed_index,istr)
                call throw_exception('Error in push_char: '//&
                                     'invalid valid of pushed_index: '//trim(istr))
            end if
        end if
    end if
    end subroutine push_char
Call graph
push_char calls integer_to_string, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
parse_number calls push_char
parse_value calls push_char, parse_number, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string