real_to_string – JSON-Fortran
real_to_string Subroutine
Jacob Williams
12/4/2013
Source File
private subroutine real_to_string(rval, str)
Arguments
Type Intent Optional Attributes Name
real(kind=RK), intent(in) :: rval
real value.
character(kind=CK,len=*), intent(out) :: str
rval converted to a string.
Description
Convert a real value to a string.
Modified
Izaak Beekman : 02/24/2015 : added the compact option.
Jacob Williams : 10/27/2015 : added the star option.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: istat
Source Code
    subroutine real_to_string(rval,str)
    implicit none
    real(RK),intent(in)                  :: rval  !! real value.
    character(kind=CK,len=*),intent(out) :: str   !! rval converted to a string.
    integer(IK) :: istat
    if (real_fmt==star) then
        write(str,fmt=*,iostat=istat) rval
    else
        write(str,fmt=real_fmt,iostat=istat) rval
    end if
    if (istat==0) then
        !in this case, the default string will be compacted,
        ! so that the same value is displayed with fewer characters.
        if (compact_real) call compact_real_string(str)
    else
        str = repeat(star,len(str))
    end if
    end subroutine real_to_string
Call graph
real_to_string calls compact_real_string
json_value_print calls real_to_string, json_value_print
json_print_1 calls json_value_print
json_value_to_string calls json_value_print
json_file_print_1 calls json_value_print
json_file_print_to_console calls json_value_print
json_print calls json_print_1, json_print_2
json_print_2 calls json_print
test_2 calls json_print
test_14 calls json_print
test_12 calls json_print
test_7 calls json_print
test_4 calls json_print, json_print_to_string
test_8 calls json_print
jf_test_2 calls test_2
jf_test_14 calls test_14
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4
jf_test_8 calls test_8
json_file_print_to_string calls json_value_to_string
json_print_to_string calls json_value_to_string