rename – JSON-Fortran
rename Subroutine
Source File
public subroutine rename(p, finished)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(in), pointer :: p
logical, intent(out) :: finished
Description
change all "name" variable values to "Fred"
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: var_type
character(kind=CK,len=:), public, allocatable :: str
logical, public :: found
Source Code
    subroutine rename(p,finished)  !! change all "name" variable values to "Fred"
    implicit none
    type(json_value),pointer,intent(in) :: p
    logical,intent(out) :: finished
    integer :: var_type
    character(kind=CK,len=:),allocatable :: str
    logical :: found
    !get info about this variable:
    call json_info(p,var_type=var_type,name=str)
    !it must be a string named "name":
    if (var_type==json_string .and. str=='name') then
        call json_get(p,'@',str)             ! get original name
        call json_update(p,'@','Fred',found) !change it
        write(error_unit,'(A)') str//' name changed'
        icount = icount + 1
    end if
    !cleanup:
    if (allocated(str)) deallocate(str)
    !always false, since we want to traverse all nodes:
    finished = .false.
    end subroutine rename
Call graph
rename calls json_get, json_info, json_update
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_info calls json_count
json_update calls json_update_double, json_update_logical, json_update_string, wrap_json_update_double, wrap_json_update_integer, json_update_integer, wrap_json_update_string, json_update_string_val_ascii, json_update_string_name_ascii, wrap_json_update_logical
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path, to_unicode
json_get_double calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls json_get_double_with_path, to_unicode
json_get_double_vec calls json_get
json_get_array_with_path calls json_get_by_path, json_get_array, throw_exception, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path, to_unicode
json_get_logical calls throw_exception
json_get_logical_with_path calls json_get_by_path, json_get_logical, throw_exception, json_clear_exceptions
wrap_json_get_array_with_path calls json_get_array_with_path, to_unicode
wrap_json_get_logical_with_path calls json_get_logical_with_path, to_unicode
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path, to_unicode
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path, to_unicode
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls json_get_by_path, json_get_string, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls json_get_by_path, to_unicode
wrap_json_get_string_with_path calls json_get_string_with_path, to_unicode
json_get_integer calls throw_exception
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls json_get_integer_with_path, to_unicode
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
to_unicode calls to_uni_vec, to_uni
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls to_unicode, throw_exception
json_update_double calls json_get, json_info, throw_exception, json_add, to_double
json_update_logical calls json_get, json_info, throw_exception, json_add, to_logical
json_update_string calls json_get, json_info, throw_exception, json_add, to_string
wrap_json_update_double calls to_unicode, json_update_double
wrap_json_update_integer calls to_unicode, json_update_integer
json_update_integer calls json_get, json_info, throw_exception, json_add, to_integer
wrap_json_update_string calls to_unicode, json_update_string
json_update_string_val_ascii calls to_unicode, json_update_string
json_update_string_name_ascii calls to_unicode, json_update_string
wrap_json_update_logical calls to_unicode, json_update_logical
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
to_double calls destroy_json_data
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, to_double, json_value_create
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data