string_to_integer – JSON-Fortran
string_to_integer Function
Source File
private function string_to_integer(str) result(ival)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str
Return Value integer(kind=IK)
Description
Convert a string into an integer.
History
Jacob Williams : 12/10/2013 : Rewrote routine. Added error checking.
Modified by Izaak Beekman
Note
Replacement for the parse_integer function in the original code.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(kind=CDK,len=:), public, allocatable :: digits
integer(kind=IK), public :: ndigits_digits
integer(kind=IK), public :: ndigits
integer(kind=IK), public :: ierr
Source Code
    function string_to_integer(str) result(ival)
    implicit none
    character(kind=CK,len=*),intent(in) :: str
    integer(IK) :: ival
    character(kind=CDK,len=:),allocatable :: digits
    integer(IK) :: ndigits_digits,ndigits,ierr
    if (.not. exception_thrown) then
        ! Compute how many digits we need to read
        ndigits = 2*len_trim(str)
        ndigits_digits = floor(log10(real(ndigits)))+1
        allocate(character(kind=CDK,len=ndigits_digits) :: digits)
        write(digits,'(I0)') ndigits !gfortran will have a runtime error with * edit descriptor here
        ! gfortran bug: '*' edit descriptor for ISO_10646 strings does bad stuff.
        read(str,'(I'//trim(digits)//')',iostat=ierr) ival   !string to integer
        if (ierr/=0) then    !if there was an error
            ival = 0
            call throw_exception('Error in string_to_integer:'//&
                                 ' string cannot be converted to an integer: '//trim(str))
        end if
    else
        ival = 0
    end if
    end function string_to_integer
Call graph
string_to_integer calls throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
parse_number calls string_to_integer
json_get_by_path calls string_to_integer
parse_value calls parse_number, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_get_by_path calls json_get_by_path
json_get_array_with_path calls json_get_by_path
json_file_get_object calls json_get_by_path
json_get_integer_with_path calls json_get_by_path
json_get_double_with_path calls json_get_by_path
json_get_string_with_path calls json_get_by_path
json_get_logical_with_path calls json_get_by_path
json_get calls json_get_by_path, wrap_json_get_by_path, json_get_array_with_path, json_get_integer_with_path, json_get_double_with_path, json_get_string_with_path, json_get_logical_with_path, json_get_integer_vec_with_path, json_get_double_vec, json_get_double_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, json_get_string_vec, json_get_string_vec_with_path, json_get_integer_vec, wrap_json_get_integer_vec_with_path, wrap_json_get_double_vec_with_path, wrap_json_get_logical_vec_with_path, wrap_json_get_string_vec_with_path, wrap_json_get_array_with_path, wrap_json_get_integer_with_path, wrap_json_get_double_with_path, wrap_json_get_string_with_path, wrap_json_get_logical_with_path
json_get_integer_vec_with_path calls json_get
json_update_string calls json_get
rename calls json_get, json_update
json_file_get_integer_vec calls json_get
json_update_logical calls json_get
json_file_get_double calls json_get
json_get_double_vec calls json_get
json_file_get_string calls json_get
json_update_double calls json_get
json_get_double_vec_with_path calls json_get
test_7 calls json_get
json_file_get_logical calls json_get
json_update_integer calls json_get
json_file_get_logical_vec calls json_get
json_get_logical_vec calls json_get
json_file_get_integer calls json_get
json_get_logical_vec_with_path calls json_get
test_2 calls json_get, json_update
json_file_get_string_vec calls json_get
test_10 calls json_get, json_update, json_remove_if_present
json_file_get_double_vec calls json_get
json_get_string_vec calls json_get
json_value_remove_if_present calls json_get
json_get_string_vec_with_path calls json_get
test_12 calls json_get, json_update
json_get_integer_vec calls json_get
wrap_json_get_integer_vec_with_path calls json_get_integer_vec_with_path
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
json_update calls json_update_string, json_update_logical, json_update_double, json_update_integer, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_logical, wrap_json_update_double, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
wrap_json_file_update_real calls json_file_update_real
wrap_json_file_get_integer_vec calls json_file_get_integer_vec
wrap_json_update_logical calls json_update_logical
wrap_json_file_get_double calls json_file_get_double
wrap_json_file_get_string calls json_file_get_string
wrap_json_update_double calls json_update_double
wrap_json_get_double_vec_with_path calls json_get_double_vec_with_path
jf_test_7 calls test_7
wrap_json_file_get_logical calls json_file_get_logical
wrap_json_update_integer calls json_update_integer
wrap_json_file_get_logical_vec calls json_file_get_logical_vec
wrap_json_file_get_integer calls json_file_get_integer
wrap_json_get_logical_vec_with_path calls json_get_logical_vec_with_path
jf_test_2 calls test_2
wrap_json_file_get_string_vec calls json_file_get_string_vec
jf_test_10 calls test_10
wrap_json_file_get_double_vec calls json_file_get_double_vec
wrap_json_value_remove_if_present calls json_value_remove_if_present
json_remove_if_present calls json_value_remove_if_present, wrap_json_value_remove_if_present
wrap_json_get_string_vec_with_path calls json_get_string_vec_with_path
jf_test_12 calls test_12
wrap_json_get_array_with_path calls json_get_array_with_path
wrap_json_file_get_object calls json_file_get_object
wrap_json_get_integer_with_path calls json_get_integer_with_path
wrap_json_get_double_with_path calls json_get_double_with_path
wrap_json_get_string_with_path calls json_get_string_with_path
wrap_json_get_logical_with_path calls json_get_logical_with_path