test_8 – JSON-Fortran
test_8 Subroutine
Source File
public subroutine test_8(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
Description
read a JSON structure from a string
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: p
character(len=*), public, parameter :: newline = achar(10)
character(len=*), public, parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
character(len=*), public, parameter :: str2 = '{ "label": "foo",'//newline//' "value": "bar",'//newline//' "empty_array": [],'//newline//' "empty_object": {}'//newline//'}'
character(len=*), public, parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
Source Code
    subroutine test_8(error_cnt)
    !! read a JSON structure from a string
    implicit none
    integer,intent(out) :: error_cnt
    type(json_value),pointer :: p
    character(len=*),parameter :: newline = achar(10)
    character(len=*),parameter :: str = '{ "label": "foo",'//newline//' "value": "bar" }'
    character(len=*),parameter :: str2 = '{ "label": "foo",'//newline//&
                                         '  "value": "bar",'//newline//&
                                         '  "empty_array": [],'//newline//&
                                         '  "empty_object": {}' //newline//&
                                         '}'
    character(len=*),parameter :: str_invalid = '{ "label": "foo",'//newline//' "value : "bar" }'
    error_cnt = 0
    call json_initialize()
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   EXAMPLE 8 : read JSON from string'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 1:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '{ "part a" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Valid test 2:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str2, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part b" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') ','
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ' Invalid test:'
    write(error_unit,'(A)') '**************'
    write(error_unit,'(A)') ''
    call json_parse(str=str_invalid, p=p)   ! read it from str
    if (json_failed()) then
        call json_print_error_message(error_unit)
    else
        write(error_unit,'(A)') 'This should have failed!'
        error_cnt = error_cnt + 1
    end if
    write(output_unit,'(A)') '"part c" : '
    call json_print(p,output_unit)  ! print to console
    write(output_unit,'(A)') '}'
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_destroy(p)            ! cleanup
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    write(error_unit,'(A)') ''
    end subroutine test_8
Call graph
test_8 calls json_failed, json_print_error_message, json_destroy, json_initialize, json_print, json_parse
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_destroy calls json_value_destroy
json_initialize calls json_clear_exceptions, throw_exception
json_print calls json_print_1, json_print_2
json_parse calls json_parse_file, wrap_json_parse_string, json_parse_string
json_value_destroy calls json_value_destroy, destroy_json_data
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls throw_exception, json_value_print, json_count, write_it, real_to_string, integer_to_string
real_to_string calls compact_real_string
json_parse_file calls json_initialize, throw_exception, json_value_create, annotate_invalid_json, parse_value
wrap_json_parse_string calls to_unicode, json_parse_string
json_parse_string calls json_initialize, json_value_create, annotate_invalid_json, parse_value
annotate_invalid_json calls integer_to_string, get_current_line_from_file_stream, get_current_line_from_file_sequential
parse_value calls throw_exception, parse_array, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object, pop_char
parse_array calls json_destroy, throw_exception, json_value_create, parse_value, pop_char, json_add
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, push_char, pop_char, to_integer, to_double, string_to_integer, string_to_double
parse_object calls json_destroy, throw_exception, json_value_create, parse_value, parse_string, parse_object, pop_char, json_add
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_value_create, json_add, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_integer calls destroy_json_data
to_double calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
jf_test_8 calls test_8