test_14 – JSON-Fortran
test_14 Subroutine
Source File
public subroutine test_14(error_cnt)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: error_cnt
report number of errors to caller
Description
Tests the traversal of a JSON structure
It traverses the structure, looks for all "name" variables, and changes the name.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(json_value), public, pointer :: json
Source Code
    subroutine test_14(error_cnt)
    !! Tests the traversal of a JSON structure
    !!
    !! It traverses the structure, looks for all "name" variables, and changes the name.
    implicit none
    integer,intent(out) :: error_cnt !! report number of errors to caller
    type(json_value),pointer  :: json
    write(error_unit,'(A)') ''
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') '   TEST 14'
    write(error_unit,'(A)') '================================='
    write(error_unit,'(A)') ''
    error_cnt = 0
    icount = 0 !number of name changes (should be 2)
    call json_initialize() !initialize the module
    call json_parse(dir//filename1,json)  !read the file
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    call json_traverse(json,rename) !traverse all nodes in the structure
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    if (icount/=2) then
        write(error_unit,'(A)') 'Error: should be 2 "name" variables in this file: '//filename1
        error_cnt = error_cnt + 1
    end if
    if (error_cnt==0) then
        write(error_unit,'(A)') ''
        write(error_unit,'(A)') ' All names changed to Fred:'
        write(error_unit,'(A)') ''
        call json_print(json,output_unit)
        write(error_unit,'(A)') ''
    end if
    call json_destroy(json)  !clean up
    if (json_failed()) then
        call json_print_error_message(error_unit)
        error_cnt = error_cnt + 1
    end if
    end subroutine test_14
Call graph
test_14 calls json_print_error_message, json_parse, json_initialize, json_destroy, json_traverse, json_print, json_failed
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_parse calls json_parse_file, wrap_json_parse_string, json_parse_string
json_initialize calls json_clear_exceptions, throw_exception
json_destroy calls json_value_destroy
json_traverse calls json_traverse, json_count
json_print calls json_print_1, json_print_2
json_parse_file calls json_initialize, json_value_create, annotate_invalid_json, parse_value, throw_exception
wrap_json_parse_string calls json_parse_string, to_unicode
json_parse_string calls json_initialize, json_value_create, annotate_invalid_json, parse_value
annotate_invalid_json calls get_current_line_from_file_stream, integer_to_string, get_current_line_from_file_sequential
parse_value calls throw_exception, parse_array, to_logical, push_char, to_null, parse_string, to_array, to_string, to_object, parse_for_chars, parse_number, parse_object, pop_char
throw_exception calls json_throw_exception, wrap_json_throw_exception
parse_array calls json_destroy, json_value_create, parse_value, throw_exception, pop_char, json_add
to_logical calls destroy_json_data
push_char calls throw_exception, integer_to_string
to_null calls destroy_json_data
parse_string calls throw_exception, pop_char, valid_json_hex
to_array calls destroy_json_data
to_string calls destroy_json_data
to_object calls destroy_json_data
parse_for_chars calls throw_exception, pop_char
parse_number calls throw_exception, push_char, pop_char, to_integer, to_double, string_to_integer, string_to_double
parse_object calls json_destroy, json_value_create, parse_value, throw_exception, parse_string, parse_object, pop_char, json_add
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_value_create, to_array, json_add
json_value_add_string_vec calls json_value_create, to_array, json_add
json_value_add_logical_vec calls json_value_create, to_array, json_add
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_value_create, json_add, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_value_create, to_array, json_add
json_value_add_double calls json_value_create, json_add, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_value_create, to_logical, json_add
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_value_create, to_string, json_add, escape_string
to_unicode calls to_uni_vec, to_uni
to_integer calls destroy_json_data
to_double calls destroy_json_data
string_to_integer calls throw_exception
string_to_double calls throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
json_value_destroy calls destroy_json_data, json_value_destroy
json_print_1 calls throw_exception, json_value_print
json_print_2 calls json_print, throw_exception
json_value_print calls throw_exception, integer_to_string, json_count, json_value_print, write_it, real_to_string
real_to_string calls compact_real_string
jf_test_14 calls test_14