to_integer – JSON-Fortran
to_integer Subroutine
Jacob Williams
Source File
private subroutine to_integer(me, val, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(inout) :: me
integer(kind=IK), intent(in), optional :: val
if the value is also to be set (if not present, then 0 is used).
character(kind=CK,len=*), intent(in), optional :: name
if the name is also to be changed.
Description
Change the json_value variable to an integer.
Calls
Called By
Source Code
    subroutine to_integer(me,val,name)
    implicit none
    type(json_value),intent(inout)               :: me
    integer(IK),intent(in),optional              :: val   !! if the value is also to be set (if not present, then 0 is used).
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    !set type and value:
    call destroy_json_data(me)
    me%var_type = json_integer
    allocate(me%int_value)
    if (present(val)) then
        me%int_value = val
    else
        me%int_value = 0    !default value
    end if
    !name:
    if (present(name)) me%name = trim(name)
    end subroutine to_integer
Call graph
to_integer calls destroy_json_data
parse_number calls to_integer
json_value_add_integer calls to_integer, json_add
json_value_create_integer calls to_integer
json_update_integer calls to_integer, json_add
parse_value calls parse_number, parse_object, parse_array
json_parse_file calls parse_value
parse_object calls parse_value, parse_object, json_add
json_parse_string calls parse_value
parse_array calls parse_value, json_add
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_value_add_integer calls json_value_add_integer
json_add calls json_value_add_integer, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_double_vec, json_value_add_double, json_value_add_string, json_value_add_logical, wrap_json_value_add_integer_vec, json_value_add_string_vec_name_ascii, wrap_json_value_add_string_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_logical_vec, wrap_json_value_add_double_vec, wrap_json_value_add_double, json_value_add_string_name_ascii, wrap_json_value_add_string, json_value_add_string_val_ascii, wrap_json_value_add_logical
json_value_add_integer_vec calls json_add
json_value_add_string_vec calls json_add
json_value_add_logical_vec calls json_add
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
test_2 calls json_add, add_variables_to_input, json_update
json_value_add_double_vec calls json_add
test_12 calls json_add, json_update
json_value_add_double calls json_add
test_7 calls json_add
json_value_add_string calls json_add
json_value_add_logical calls json_add
test_4 calls json_add
add_variables_to_input calls json_add
wrap_json_value_add_integer_vec calls json_value_add_integer_vec
json_value_add_string_vec_name_ascii calls json_value_add_string_vec
wrap_json_value_add_string_vec calls json_value_add_string_vec
json_value_add_string_vec_val_ascii calls json_value_add_string_vec
wrap_json_value_add_logical_vec calls json_value_add_logical_vec
wrap_json_update_logical calls json_update_logical
json_update calls json_update_integer, json_update_logical, json_update_double, json_update_string, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update, json_create_integer
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
jf_test_2 calls test_2
wrap_json_value_add_double_vec calls json_value_add_double_vec
jf_test_12 calls test_12
wrap_json_value_add_double calls json_value_add_double
jf_test_7 calls test_7
json_value_add_string_name_ascii calls json_value_add_string
wrap_json_value_add_string calls json_value_add_string
json_value_add_string_val_ascii calls json_value_add_string
wrap_json_value_add_logical calls json_value_add_logical
jf_test_4 calls test_4
wrap_json_value_create_integer calls json_value_create_integer
json_create_integer calls json_value_create_integer, wrap_json_value_create_integer
wrap_json_update_integer calls json_update_integer