to_null – JSON-Fortran
to_null Subroutine
Jacob Williams
Source File
private subroutine to_null(me, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(inout) :: me
character(kind=CK,len=*), intent(in), optional :: name
if the name is also to be changed.
Description
Change the json_value variable to a null.
Calls
Called By
Source Code
    subroutine to_null(me,name)
    implicit none
    type(json_value),intent(inout)               :: me
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    !set type and value:
    call destroy_json_data(me)
    me%var_type = json_null
    !name:
    if (present(name)) me%name = trim(name)
    end subroutine to_null
Call graph
to_null calls destroy_json_data
json_value_create_null calls to_null
parse_value calls to_null, parse_object, parse_array
wrap_json_value_create_null calls json_value_create_null
json_create_null calls json_value_create_null, wrap_json_value_create_null
test_10 calls json_create_null
jf_test_10 calls test_10
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string