to_object – JSON-Fortran
to_object Subroutine
Jacob Williams
Source File
private subroutine to_object(me, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), intent(inout) :: me
character(kind=CK,len=*), intent(in), optional :: name
if the name is also to be changed.
Description
Change the json_value variable to an object.
Calls
Called By
Source Code
    subroutine to_object(me,name)
    implicit none
    type(json_value),intent(inout)               :: me
    character(kind=CK,len=*),intent(in),optional :: name  !! if the name is also to be changed.
    !set type and value:
    call destroy_json_data(me)
    me%var_type = json_object
    !name:
    if (present(name)) me%name = trim(name)
    end subroutine to_object
Call graph
to_object calls destroy_json_data
json_value_create_object calls to_object
parse_value calls to_object, parse_object, parse_array
wrap_json_value_create_object calls json_value_create_object
json_create_object calls json_value_create_object, wrap_json_value_create_object
test_7 calls json_create_object
test_2 calls json_create_object, add_variables_to_input
add_variables_to_input calls json_create_object
test_12 calls json_create_object
test_10 calls json_create_object
test_4 calls json_create_object
jf_test_7 calls test_7
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_10 calls test_10
jf_test_4 calls test_4
json_parse_file calls parse_value
parse_object calls parse_value, parse_object
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string