valid_json_hex – JSON-Fortran
valid_json_hex Function
Jacob Williams
6/14/2014
Source File
private pure function valid_json_hex(str) result(valid)
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str
the string to check.
Return Value logical(kind=LK)
is str a value 4-digit hex string
Description
Returns true if the string is a valid 4-digit hex string.
Examples
    valid_json_hex('0000')  !returns true
    valid_json_hex('ABC4')  !returns true
    valid_json_hex('AB')    !returns false (< 4 characters)
    valid_json_hex('WXYZ')  !returns false (invalid characters)
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), public :: n
integer(kind=IK), public :: i
character(kind=CK,len=1), public, parameter, dimension(22) :: valid_chars = [(achar(i), i=48, 57), (achar(i), i=65, 70), (achar(i), i=97, 102)]
Source Code
    pure function valid_json_hex(str) result(valid)
    implicit none
    logical(LK)                         :: valid  !! is str a value 4-digit hex string
    character(kind=CK,len=*),intent(in) :: str    !! the string to check.
    integer(IK) :: n,i
    !an array of the valid hex characters:
    character(kind=CK,len=1),dimension(22),parameter :: valid_chars = &
        [ (achar(i),i=48,57), & ! decimal digits
          (achar(i),i=65,70), & ! capital A-F
          (achar(i),i=97,102) ] ! lowercase a-f
    !initialize
    valid = .false.
    !check all the characters in the string:
    n = len(str)
    if (n==4) then
        do i=1,n
            if (.not. any(str(i:i)==valid_chars)) return
        end do
        valid = .true.    !all are in the set, so it is OK
    end if
    end function valid_json_hex
Call graph
parse_string calls valid_json_hex
parse_object calls parse_string, parse_object, parse_value
parse_value calls parse_string, parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
parse_array calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string