wrap_json_file_get_string_vec – JSON-Fortran
wrap_json_file_get_string_vec Subroutine
Source File
private subroutine wrap_json_file_get_string_vec(me, path, vec, found)
Arguments
Type Intent Optional Attributes Name
class(json_file), intent(inout) :: me
character(kind=CDK,len=*), intent(in) :: path
character(kind=CK,len=*), intent(out), dimension(:), allocatable :: vec
logical(kind=LK), intent(out), optional :: found
Description
Alternate version of json_file_get_string_vec, where "path" is kind=CDK.
Calls
Source Code
    subroutine wrap_json_file_get_string_vec(me, path, vec, found)
    implicit none
    class(json_file),intent(inout)                                :: me
    character(kind=CDK,len=*),intent(in)                          :: path
    character(kind=CK,len=*),dimension(:),allocatable,intent(out) :: vec
    logical(LK),intent(out),optional                              :: found
    call json_file_get_string_vec(me, to_unicode(path), vec, found)
    end subroutine wrap_json_file_get_string_vec
Call graph
wrap_json_file_get_string_vec calls json_file_get_string_vec, to_unicode
json_file_get_string_vec calls json_get
to_unicode calls to_uni_vec, to_uni
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls json_get_by_path, json_get_array, throw_exception, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls json_get_by_path, json_get_logical, throw_exception, json_clear_exceptions
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls json_get_by_path, json_get_string, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer calls throw_exception
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls to_unicode, throw_exception