json_add – JSON-Fortran
json_add Interface
Source File
public interface json_add
Add objects to a linked list of json_values.
Note
Formerly, this was called json_value_add
Calls
Called By
Module Procedures
private subroutine json_value_add_member(me, member)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
type(json_value), , pointer :: member
the child member to add
Description
Adds "member" as a child of "me".
private subroutine json_value_add_integer(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
Description
Author
Jacob Williams
Date
1/20/2014
Add an integer value child to the json_value variable
private subroutine wrap_json_value_add_integer(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in) :: val
value
Description
Alternate version of json_value_add_integer where "name" is kind=CDK.
private subroutine json_value_add_integer_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in), dimension(:) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add an integer vector to the structure.
private subroutine wrap_json_value_add_integer_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
integer(kind=IK), intent(in), dimension(:) :: val
value
Description
Alternate version of json_value_add_integer_vec where "name" is kind=CDK.
private subroutine json_value_add_double(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
variable name
real(kind=RK), intent(in) :: val
real value
Description
Author
Jacob Williams
Date
1/19/2014
Add a real value child to the json_value variable
private subroutine wrap_json_value_add_double(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
variable name
real(kind=RK), intent(in) :: val
real value
Description
Alternate version of json_value_add_double where "name" is kind=CDK.
private subroutine json_value_add_double_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
real(kind=RK), intent(in), dimension(:) :: val
Description
Author
Jacob Williams
Date
1/20/2014
Add a real vector to the structure.
private subroutine wrap_json_value_add_double_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
real(kind=RK), intent(in), dimension(:) :: val
Description
Alternate version of json_value_add_double_vec where "name" is kind=CDK.
private subroutine json_value_add_logical(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add a logical value child to the json_value variable
private subroutine wrap_json_value_add_logical(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in) :: val
value
Description
Alternate version of json_value_add_logical where "name" is kind=CDK.
private subroutine json_value_add_logical_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the vector
logical(kind=LK), intent(in), dimension(:) :: val
value
Description
Author
Jacob Williams
Date
1/20/2014
Add a logical vector to the structure.
private subroutine wrap_json_value_add_logical_vec(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
logical(kind=LK), intent(in), dimension(:) :: val
value
Description
Alternate version of json_value_add_logical_vec where "name" is kind=CDK.
private subroutine json_value_add_string(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
character(kind=CK,len=*), intent(in) :: val
value
Description
Author
Jacob Williams
Date
1/19/2014
Add a character string child to the json_value variable.
private subroutine wrap_json_value_add_string(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
character(kind=CDK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "name" and "val" are kind=CDK.
private subroutine json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
variable name
character(kind=CK,len=*), intent(in), dimension(:) :: val
array of strings
logical(kind=LK), intent(in), optional :: trim_str
if TRIM() should be called for each element
logical(kind=LK), intent(in), optional :: adjustl_str
if ADJUSTL() should be called for each element
Description
Author
Jacob Williams
Date
1/19/2014
Add an array of character strings to the structure.
private subroutine wrap_json_value_add_string_vec(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "name" and "val" are kind=CDK.
private subroutine json_value_add_string_name_ascii(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
name of the variable
character(kind=CK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "name" is kind=CDK.
private subroutine json_value_add_string_val_ascii(me, name, val)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
name of the variable
character(kind=CDK,len=*), intent(in) :: val
value
Description
Alternate version of json_value_add_string where "val" is kind=CDK.
private subroutine json_value_add_string_vec_name_ascii(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CDK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "name" is kind=CDK.
private subroutine json_value_add_string_vec_val_ascii(me, name, val, trim_str, adjustl_str)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
character(kind=CK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in), dimension(:) :: val
logical(kind=LK), intent(in), optional :: trim_str
logical(kind=LK), intent(in), optional :: adjustl_str
Description
Alternate version of json_value_add_string_vec where "val" is kind=CDK.
Call graph
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_value_add_string_name_ascii calls json_value_add_string, to_unicode
wrap_json_value_add_integer calls json_value_add_integer, to_unicode
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls json_value_add_string_vec, to_unicode
wrap_json_value_add_integer_vec calls json_value_add_integer_vec, to_unicode
wrap_json_value_add_string_vec calls json_value_add_string_vec, to_unicode
wrap_json_value_add_double_vec calls json_value_add_double_vec, to_unicode
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls json_value_add_string, to_unicode
wrap_json_value_add_double calls json_value_add_double, to_unicode
json_value_add_string_vec_name_ascii calls json_value_add_string_vec, to_unicode
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, json_value_create, to_double
wrap_json_value_add_logical_vec calls json_value_add_logical_vec, to_unicode
json_value_add_string_val_ascii calls json_value_add_string, to_unicode
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls json_value_add_logical, to_unicode
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_unicode calls to_uni_vec, to_uni
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_double calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
parse_object calls json_add, parse_object, parse_value
parse_array calls json_add, parse_value
json_update_logical calls json_add
json_update_double calls json_add
json_update_string calls json_add
json_update_integer calls json_add
test_2 calls json_add, add_variables_to_input, json_update
test_12 calls json_add, json_update
test_7 calls json_add
test_4 calls json_add
add_variables_to_input calls json_add
parse_value calls parse_object, parse_array
json_parse_file calls parse_value
json_parse_string calls parse_value
json_parse calls json_parse_file, json_parse_string, wrap_json_parse_string
json_file_load calls json_parse
test_14 calls json_parse
test_8 calls json_parse
json_file_load_from_string calls json_parse
jf_test_14 calls test_14
jf_test_8 calls test_8
wrap_json_file_load_from_string calls json_file_load_from_string
wrap_json_parse_string calls json_parse_string
wrap_json_update_logical calls json_update_logical
json_update calls json_update_logical, json_update_double, json_update_string, json_update_integer, wrap_json_update_logical, wrap_json_update_double, json_update_string_name_ascii, wrap_json_update_string, json_update_string_val_ascii, wrap_json_update_integer
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
json_file_update_real calls json_update
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
wrap_json_file_update_real calls json_file_update_real
wrap_json_update_double calls json_update_double
json_update_string_name_ascii calls json_update_string
wrap_json_update_string calls json_update_string
json_update_string_val_ascii calls json_update_string
wrap_json_update_integer calls json_update_integer
jf_test_2 calls test_2
jf_test_12 calls test_12
jf_test_7 calls test_7
jf_test_4 calls test_4