json_remove_if_present – JSON-Fortran
json_remove_if_present Interface
Source File
public interface json_remove_if_present
If the child variable is present, then remove it.
Calls
Called By
Module Procedures
private subroutine json_value_remove_if_present(p, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, remove the variable from the json_value structure, if it exists.
private subroutine wrap_json_value_remove_if_present(p, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
Description
Alternate version of json_value_remove_if_present, where "name" is kind=CDK.
Call graph
json_remove_if_present calls wrap_json_value_remove_if_present, json_value_remove_if_present
wrap_json_value_remove_if_present calls json_value_remove_if_present, to_unicode
json_value_remove_if_present calls json_get, json_remove
to_unicode calls to_uni_vec, to_uni
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_remove calls json_value_remove
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls json_get_double, json_get_by_path, throw_exception, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls json_get_by_path, json_get_array, throw_exception, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls json_get_by_path, json_get_logical, throw_exception, json_clear_exceptions
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls json_get_by_path, json_get_string, throw_exception, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer calls throw_exception
json_get_integer_with_path calls json_get_by_path, json_get_integer, throw_exception, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls to_unicode, json_throw_exception
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls to_unicode, throw_exception
json_value_remove calls json_value_destroy
json_value_destroy calls json_value_destroy, destroy_json_data
test_10 calls json_remove_if_present
jf_test_10 calls test_10