json_create_double – JSON-Fortran
json_create_double Interface
Source File
public interface json_create_double
Allocate a json_value pointer and make it a double variable. The pointer should not already be allocated.
Example
    type(json_value),pointer :: p
    call json_create_double(p,'value',1.0d0)
Calls
Called By
Module Procedures
private subroutine json_value_create_double(me, val, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
real(kind=RK), intent(in) :: val
character(kind=CK,len=*), intent(in) :: name
Description
Author
Jacob Williams
Allocate a json_value pointer and make it a real(RK) variable. The pointer should not already be allocated.
private subroutine wrap_json_value_create_double(me, val, name)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: me
real(kind=RK), intent(in) :: val
character(kind=CDK,len=*), intent(in) :: name
Description
Author
Izaak Beekman
A wrapper for json_value_create_double so that json_create_double may be called with an actual argument corresponding to the dummy argument, 'name' that may be of 'DEFAULT' or 'ISO_10646' character kind.
Call graph
json_create_double calls json_value_create_double, wrap_json_value_create_double
json_value_create_double calls json_value_create, to_double
wrap_json_value_create_double calls json_value_create_double, to_unicode
to_double calls destroy_json_data
to_unicode calls to_uni_vec, to_uni
test_10 calls json_create_double
jf_test_10 calls test_10