json_update – JSON-Fortran
json_update Interface
Source File
public interface json_update
These are like json_add, except if a child with the same name is already present, then its value is simply updated. Note that currently, these only work for scalar variables. These routines can also change the variable's type (but an error will be thrown if the existing variable is not a scalar).
Note
It should not be used to change the type of a variable in an array, or it may result in an invalid JSON file.
Calls
Called By
Module Procedures
private subroutine json_update_logical(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
logical(kind=LK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_logical(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
logical(kind=LK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_logical, where "name" is kind=CDK.
private subroutine json_update_double(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
real(kind=RK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_double(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
real(kind=RK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_double, where "name" is kind=CDK.
private subroutine json_update_integer(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_integer(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
integer(kind=IK), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_integer, where "name" is kind=CDK.
private subroutine json_update_string(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Author
Jacob Williams
Date
12/6/2014
Given the path string, if the variable is present, and is a scalar, then update its value. If it is not present, then create it and set its value.
private subroutine wrap_json_update_string(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "name" and "value" are kind=CDK.
private subroutine json_update_string_name_ascii(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CDK,len=*), intent(in) :: name
character(kind=CK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "name" is kind=CDK.
private subroutine json_update_string_val_ascii(p, name, val, found)
Arguments
Type Intent Optional Attributes Name
type(json_value), , pointer :: p
character(kind=CK,len=*), intent(in) :: name
character(kind=CDK,len=*), intent(in) :: val
logical(kind=LK), intent(out) :: found
Description
Alternate version of json_update_string, where "val" is kind=CDK.
Call graph
json_update calls json_update_double, json_update_logical, json_update_string, wrap_json_update_double, wrap_json_update_integer, json_update_integer, wrap_json_update_string, json_update_string_val_ascii, json_update_string_name_ascii, wrap_json_update_logical
json_update_double calls throw_exception, json_get, json_add, json_info, to_double
json_update_logical calls throw_exception, json_get, json_add, json_info, to_logical
json_update_string calls throw_exception, json_get, json_add, json_info, to_string
wrap_json_update_double calls json_update_double, to_unicode
wrap_json_update_integer calls json_update_integer, to_unicode
json_update_integer calls throw_exception, json_get, json_add, json_info, to_integer
wrap_json_update_string calls json_update_string, to_unicode
json_update_string_val_ascii calls json_update_string, to_unicode
json_update_string_name_ascii calls json_update_string, to_unicode
wrap_json_update_logical calls json_update_logical, to_unicode
throw_exception calls json_throw_exception, wrap_json_throw_exception
json_get calls json_get_integer_vec_with_path, wrap_json_get_integer_vec_with_path, json_get_double, json_get_double_with_path, json_get_by_path, wrap_json_get_double_with_path, json_get_double_vec, json_get_array_with_path, json_get_double_vec_with_path, json_get_string_vec_with_path, wrap_json_get_double_vec_with_path, json_get_logical, json_get_logical_with_path, wrap_json_get_array_with_path, wrap_json_get_logical_with_path, wrap_json_get_string_vec_with_path, json_get_logical_vec, json_get_logical_vec_with_path, wrap_json_get_logical_vec_with_path, json_get_string, json_get_string_with_path, wrap_json_get_by_path, wrap_json_get_string_with_path, json_get_integer, json_get_integer_with_path, wrap_json_get_integer_with_path, json_get_string_vec, json_get_array, json_get_integer_vec
json_add calls json_value_add_string_name_ascii, wrap_json_value_add_integer, json_value_add_integer_vec, json_value_add_string_vec, json_value_add_logical_vec, json_value_add_string_vec_val_ascii, wrap_json_value_add_integer_vec, wrap_json_value_add_string_vec, wrap_json_value_add_double_vec, json_value_add_integer, wrap_json_value_add_string, wrap_json_value_add_double, json_value_add_string_vec_name_ascii, json_value_add_double_vec, json_value_add_double, wrap_json_value_add_logical_vec, json_value_add_string_val_ascii, json_value_add_logical, wrap_json_value_add_logical, json_value_add_string, json_value_add_member
json_info calls json_count
to_double calls destroy_json_data
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni
json_get_integer_vec_with_path calls json_get
wrap_json_get_integer_vec_with_path calls to_unicode, json_get_integer_vec_with_path
json_get_double calls throw_exception
json_get_double_with_path calls throw_exception, json_get_double, json_get_by_path, json_clear_exceptions
json_get_by_path calls throw_exception, json_clear_exceptions, string_to_integer, json_get_child
wrap_json_get_double_with_path calls to_unicode, json_get_double_with_path
json_get_double_vec calls json_get
json_get_array_with_path calls throw_exception, json_get_by_path, json_get_array, json_clear_exceptions
json_get_double_vec_with_path calls json_get
json_get_string_vec_with_path calls json_get
wrap_json_get_double_vec_with_path calls to_unicode, json_get_double_vec_with_path
json_get_logical calls throw_exception
json_get_logical_with_path calls throw_exception, json_get_by_path, json_get_logical, json_clear_exceptions
wrap_json_get_array_with_path calls to_unicode, json_get_array_with_path
wrap_json_get_logical_with_path calls to_unicode, json_get_logical_with_path
wrap_json_get_string_vec_with_path calls to_unicode, json_get_string_vec_with_path
json_get_logical_vec calls json_get
json_get_logical_vec_with_path calls json_get
wrap_json_get_logical_vec_with_path calls to_unicode, json_get_logical_vec_with_path
json_get_string calls throw_exception, unescape_string
json_get_string_with_path calls throw_exception, json_get_by_path, json_get_string, json_clear_exceptions
wrap_json_get_by_path calls to_unicode, json_get_by_path
wrap_json_get_string_with_path calls to_unicode, json_get_string_with_path
json_get_integer calls throw_exception
json_get_integer_with_path calls throw_exception, json_get_by_path, json_get_integer, json_clear_exceptions
wrap_json_get_integer_with_path calls to_unicode, json_get_integer_with_path
json_get_string_vec calls json_get
json_get_array calls throw_exception, json_count
json_get_integer_vec calls json_get
string_to_integer calls throw_exception
json_get_child calls json_value_get_by_name_chars, json_value_get_by_index, wrap_json_value_get_by_name_chars
json_value_get_by_name_chars calls throw_exception, json_count
json_value_get_by_index calls throw_exception
wrap_json_value_get_by_name_chars calls to_unicode, json_value_get_by_name_chars
unescape_string calls throw_exception, to_unicode
json_value_add_string_name_ascii calls to_unicode, json_value_add_string
wrap_json_value_add_integer calls to_unicode, json_value_add_integer
json_value_add_integer_vec calls json_add, json_value_create, to_array
json_value_add_string_vec calls json_add, json_value_create, to_array
json_value_add_logical_vec calls json_add, json_value_create, to_array
json_value_add_string_vec_val_ascii calls to_unicode, json_value_add_string_vec
wrap_json_value_add_integer_vec calls to_unicode, json_value_add_integer_vec
wrap_json_value_add_string_vec calls to_unicode, json_value_add_string_vec
wrap_json_value_add_double_vec calls to_unicode, json_value_add_double_vec
json_value_add_integer calls json_add, json_value_create, to_integer
wrap_json_value_add_string calls to_unicode, json_value_add_string
wrap_json_value_add_double calls to_unicode, json_value_add_double
json_value_add_string_vec_name_ascii calls to_unicode, json_value_add_string_vec
json_value_add_double_vec calls json_add, json_value_create, to_array
json_value_add_double calls json_add, to_double, json_value_create
wrap_json_value_add_logical_vec calls to_unicode, json_value_add_logical_vec
json_value_add_string_val_ascii calls to_unicode, json_value_add_string
json_value_add_logical calls json_add, json_value_create, to_logical
wrap_json_value_add_logical calls to_unicode, json_value_add_logical
json_value_add_string calls json_add, json_value_create, escape_string, to_string
to_array calls destroy_json_data
to_integer calls destroy_json_data
to_logical calls destroy_json_data
to_string calls destroy_json_data
test_12 calls json_update
json_file_update_string calls json_update
json_file_update_integer calls json_update
json_file_update_logical calls json_update
test_1 calls json_update
rename calls json_update
test_10 calls json_update
test_2 calls json_update
json_file_update_real calls json_update
jf_test_12 calls test_12
wrap_json_file_update_string calls json_file_update_string
json_file_update_string_name_ascii calls json_file_update_string
json_file_update_string_val_ascii calls json_file_update_string
wrap_json_file_update_integer calls json_file_update_integer
wrap_json_file_update_logical calls json_file_update_logical
jf_test_1 calls test_1
jf_test_10 calls test_10
jf_test_2 calls test_2
wrap_json_file_update_real calls json_file_update_real