to_unicode – JSON-Fortran
to_unicode Interface
Source File
public interface to_unicode
Convert a 'DEFAULT' kind character input to 'ISO_10646' kind and return it
Calls
Called By
Module Procedures
private pure function to_uni(str)
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in) :: str
Return Value character(kind=CK,len=len(str))
Description
Author
Izaak Beekman
Convert string to unicode (CDK to CK).
private pure function to_uni_vec(str)
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in), dimension(:) :: str
Return Value character(kind=CK,len=len(str)), dimension(size(str))
Description
Author
Izaak Beekman
Convert array of strings to unicode (CDK to CK).
Call graph
to_unicode calls to_uni, to_uni_vec
wrap_json_get_double_with_path calls to_unicode
wrap_json_value_create_array calls to_unicode
wrap_json_file_get_double calls to_unicode
json_value_add_string_name_ascii calls to_unicode
ucs4_join_default calls to_unicode
wrap_json_value_remove_if_present calls to_unicode
wrap_json_file_get_double_vec calls to_unicode
wrap_json_value_create_string calls to_unicode
wrap_json_throw_exception calls to_unicode
default_join_ucs4 calls to_unicode
wrap_json_get_array_with_path calls to_unicode
wrap_json_value_add_integer_vec calls to_unicode
wrap_json_value_add_logical_vec calls to_unicode
wrap_json_value_create_logical calls to_unicode
ucs4_comp_default calls to_unicode
json_value_add_string_vec_name_ascii calls to_unicode
wrap_json_file_get_logical calls to_unicode
json_value_add_string_val_ascii calls to_unicode
default_comp_ucs4 calls to_unicode
wrap_json_value_add_string_vec calls to_unicode
wrap_json_file_get_logical_vec calls to_unicode
wrap_json_value_create_null calls to_unicode
wrap_json_get_integer_vec_with_path calls to_unicode
ucs4_neq_default calls to_unicode
wrap_json_value_create_double calls to_unicode
wrap_json_file_variable_info calls to_unicode
wrap_json_get_integer_with_path calls to_unicode
default_neq_ucs4 calls to_unicode
wrap_json_value_get_by_name_chars calls to_unicode
wrap_json_file_get_string calls to_unicode
wrap_json_update_logical calls to_unicode
wrap_json_update_integer calls to_unicode
wrap_json_get_string_vec_with_path calls to_unicode
wrap_json_file_get_string_vec calls to_unicode
wrap_json_value_add_double calls to_unicode
wrap_json_get_double_vec_with_path calls to_unicode
wrap_json_file_get_integer calls to_unicode
wrap_json_file_update_integer calls to_unicode
wrap_json_update_double calls to_unicode
wrap_json_get_by_path calls to_unicode
wrap_json_file_update_logical calls to_unicode
wrap_json_value_add_integer calls to_unicode
wrap_json_update_string calls to_unicode
wrap_json_value_create_integer calls to_unicode
wrap_json_value_create_object calls to_unicode
json_update_string_name_ascii calls to_unicode
wrap_json_parse_string calls to_unicode
json_update_string_val_ascii calls to_unicode
wrap_json_get_string_with_path calls to_unicode
wrap_json_get_logical_with_path calls to_unicode
wrap_json_file_update_real calls to_unicode
wrap_json_file_update_string calls to_unicode
wrap_json_file_get_integer_vec calls to_unicode
wrap_json_file_get_object calls to_unicode
wrap_json_value_rename calls to_unicode
json_file_update_string_name_ascii calls to_unicode
json_file_update_string_val_ascii calls to_unicode
wrap_json_value_add_string calls to_unicode
wrap_json_value_add_logical calls to_unicode
wrap_json_file_load_from_string calls to_unicode
unescape_string calls to_unicode
wrap_json_get_logical_vec_with_path calls to_unicode
wrap_json_value_add_double_vec calls to_unicode
json_value_add_string_vec_val_ascii calls to_unicode
operator(SLASHSLASH) calls ucs4_join_default, default_join_ucs4
operator(==) calls ucs4_comp_default, default_comp_ucs4
operator(SLASH=) calls ucs4_neq_default, default_neq_ucs4
json_get_string calls unescape_string