jf_test_5 – JSON-Fortran
jf_test_5 Program
Source File
Uses:
jf_test_5_mod
Fifth unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_5
    !! Fifth unit test.
    use jf_test_5_mod , only: test_5
    implicit none
    integer :: n_errors
    n_errors = 0
    call test_5(n_errors)
    if (n_errors /= 0) stop 1
end program jf_test_5
Call graph
jf_test_5 calls test_5
test_5 calls json_print_error_message, json_initialize, json_failed
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_initialize calls json_clear_exceptions, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni