jf_test_13 – JSON-Fortran
jf_test_13 Program
Source File
Uses:
jf_test_13_mod
13th unit test.
Calls
Variables
Type Attributes Name Initial
integer :: n_errors
Source Code
program jf_test_13
    !! 13th unit test.
    use jf_test_13_mod, only: test_13
    implicit none
    integer :: n_errors
    call test_13(n_errors)
    if ( n_errors /= 0) stop 1
end program jf_test_13
Call graph
jf_test_13 calls test_13
test_13 calls json_print_error_message, json_initialize, json_failed
json_print_error_message calls json_clear_exceptions, json_check_for_errors
json_initialize calls json_clear_exceptions, throw_exception
throw_exception calls json_throw_exception, wrap_json_throw_exception
wrap_json_throw_exception calls json_throw_exception, to_unicode
to_unicode calls to_uni_vec, to_uni